- .github/actions/protect-branch/action.yml
- README.md
This is done automatically now when a PR is opened that
includes Flowzone, and should not need to be done manually.
> Remove branch protection rules from migration workflow

- .github/workflows/flowzone.yml
This should ensure that related jobs always download the
correct artifact.
CHange-type: patch
> Append git sha to versioned source artifact name

- .github/workflows/flowzone.yml
- README.md
It doesn't seem to matter what username we have here so might
as well set it to something generic.
Resolves: https://github.com/product-os/flowzone/issues/75
> Set ghcr.io username to flowzone

- .github/workflows/flowzone.yml
If package.json exists it would be more likely to be up-to-date.
> version_draft: Prefer version in package.json over VERSION file

- .github/workflows/flowzone.yml
Failures are still expected on merge as npm cannot overwrite a release.
> Allow PRs without a change type to publish draft releases

- .github/workflows/flowzone.yml
> Force tagging because the previous commit must not have merged

- .github/workflows/flowzone.yml
This is nearly identical to the balena publish
job but it makes it clear from the job flow what
is being done.
> Restore missing balena finalize job

- .resinci.yml
See: https://github.com/product-os/balena-concourse/pull/662
This repo still requires that resinCI be disabled via config file. Normally repos [configured with Flowzone will be ignored by resinCI](https://github.com/product-os/balena-concourse/pull/662/commits/ec5bb707973f1758ca6d370de0fed14798441f4b) but this one includes a local path to the workflow and is not detected as using Flowzone.
> Revert "Remove resinCI config"

- .github/workflows/flowzone.yml
- README.md
This will be replaced by testing a range of LTS releases
defined within the engines.node section of the package.json.
> Remove node versions input and limit to 16.x for now

- .github/workflows/flowzone.yml
We only need artifacts for the lifetime of this workflow
so there is no need for them to live longer than a few minutes.
> Set artifact retention days to 1

- .github/workflows/flowzone.yml
- README.md
- tests/docker-bake.hcl
This allows the use of advanced build options like context, dockerfile,
build args, etc.
Resolves: https://github.com/product-os/flowzone/issues/146
> Use docker-bake action if a docker-bake.hcl file is found

- .github/workflows/flowzone.yml
Special characters, especially those used by Renovate, will
fail the toJSON command.
> Avoid failure if event object cannot be parsed as JSON

- .github/workflows/flowzone.yml
The steps to download draft images, load them locally,
and push them again became redundant when the finalize step
became a matrix for each image.
> Copy directly between remote tags on docker finalize

- README.md
> Fix paths to example actions in readme

- .github/workflows/flowzone.yml
This can happen if the repo has never have a versioned PR merged.
Resolves: https://github.com/product-os/flowzone/issues/172
> Continue when the changelog cannot be generated

- .github/workflows/flowzone.yml
This should avoid accidentally leaving files behind.
Resolves: https://github.com/product-os/flowzone/issues/177
> Use tmp directory when generating changelog

- .github/actions/clean/action.yml
- .github/workflows/flowzone.yml
- README.md
Composite jobs can check additional conditions like whether
or not the PR was merged.
> Allow clean jobs to run when a PR is merged

- .github/workflows/flowzone.yml
Cancel parallel flowzone runs from the same ref that may
cause conflicts.
Resolves: https://github.com/product-os/flowzone/issues/179
> Cancel in progress jobs of the same ref

- .github/workflows/flowzone.yml
Separate branch protection job into steps
1. fetch existing branch protection object
2. parse and remove resinCI and existing flowzone checks
3. prepare new branch protection update object.
4. check result containing `required_approving_review_count`
resolves: https://github.com/product-os/flowzone/issues/111 https://github.com/product-os/flowzone/issues/141 https://github.com/product-os/flowzone/issues/140
> Add check of branch protection API call response

- .github/workflows/flowzone.yml
This can be used for installing native dependencies that are required for installing npm dependencies
> Add support for a `flowzone-preinstall` npm script

- .github/workflows/flowzone.yml
This adds the ability for the custom test/publish jobs to make use of matrices and enhances the ability to prototype matrix-using jobs for inclusion into flowzone directly
> Add support for a custom job matrices

- .github/workflows/flowzone.yml
> Use the `FLOWZONE_TOKEN` not `GITHUB_TOKEN` for publish docs

- .github/workflows/flowzone.yml
Some events like pushing a tag are valid but will not have a pull_request event body.
> Ensure finalize events always have a sha

- .github/workflows/flowzone.yml
Manual tagging of the main branch is effectively manual versioning, and would conflict with automatic Flowzone versioning.
This way Flowzone cannot be triggered by previous Flowzone versioned commits.
> Only allow tag events if versioning is disabled

- .github/workflows/flowzone.yml
This allows to work with other branches that are not the default, specifically ESR branches on meta-balena.
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> flowzone: remove check for default branch on pull request events

- .github/workflows/flowzone.yml
- README.md
It's rare that GH repo slugs align with balenaCloud application slugs so default to an empty list.
> Remove default value for balena_slugs input

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- tests/docker-bake.hcl
- tests/docker-compose.test.yml
- tests/docker-compose.yml
This commit replaces the Docker platform build/test matrix
with a single docker-compose test. It also allows multiple bake
targets for publishing image variants with unique tags.
Currently only the linux/amd64 platform image will be tested
with compose tests but any targets defined in the bake file(s)
will be published as defined.
The same cache scope is used for the compose tests as the publish
steps so targets with long build times should need to build once.
Additional cache sources can be added to the bake file(s).
Resolves: https://github.com/product-os/flowzone/issues/230
Resolves: https://github.com/product-os/flowzone/issues/253
PRs for testing:
- https://github.com/balena-io-modules/open-balena-base/pull/178
- …
> Support multiple Docker bake targets

- .github/workflows/flowzone.yml
This will allow testing of the same image that is published
by using `image: localhost:5000/sut` in a compose file.
> Combine docker tests and publish steps

- .github/workflows/flowzone.yml
> Fix typo when referencing new tag for Docker labels

- .github/workflows/flowzone.yml
This avoids issues where a PR is 1 version behind master (eg another PR was recently merged) and then the updated version for the PR branch will match the master version and give a false positive about "Failed to detect any versioned files"
> Only check for version tags from the current branch

- .github/workflows/flowzone.yml
As [discussed](https://balena.zulipchat.com/#narrow/stream/345882-_help/topic/balena-phytec.20checkout) we either change the default `fetch-depth` in project_types to `0` or we make just that configurable, which is this patch.
I'd go for the simplest approach, but that probably affects the overall speed of flowzone so this PR is a compromise with a worst UX (we use `fetch-depth` in two jobs but the global input only configures one.
> Support fetching submodule commits not in the repository HEAD

- .github/workflows/flowzone.yml
- flowzone.yml
If dev dependencies are already included in the lock file, `poetry install` installs them by default when installing the main packages.
Regardless of that we ask poetry to add the latest version of flake8, pydocstyle and pytest to the project which results in updating all dependencies from scratch and generating a new lock file, which takes ~2-3 mins on the runner if there are a lot of packages.
Now we will perform a check if the dev dependencies are installed and install them only if needed.
> Check if python dev dependencies are already installed.

- .github/workflows/flowzone.yml
- flowzone.yml
This allows tagged releases for repos where versionist is disabled.
> Provide the git describe tag if versioning is disabled

- .github/workflows/flowzone.yml
- flowzone.yml
Since compose yaml files are often used for balena deployments, and optionally for docker compose tests, let's avoid overloading the file further and ignore it when looking for bake files.
This should avoid a confusing mess of services to build when both compose files and bake files are present in a repo.
Bake files used for docker build and deploy.
Compose files used for docker compose tests and balena deploy.
> Remove docker-compose.yml from parsed bake files

- .github/workflows/flowzone.yml
- flowzone.yml
This was only being used for image pre-build and will cause issues if it depends on resources in docker-compose.yml.
> Remove compose test file from bake override

- .github/workflows/flowzone.yml
- flowzone.yml
- tests/package.json
This fixes a few bugs in those language jobs
that were preventing the post-merge run from terminating successfully.
- `github_finalize` was missing a step to download the sources
- `cargo_publish` was wrongly failing if `CARGO_REGISTRY_TOKEN` was
empty
- `npm_finalize` was failing because the test package publishing was
conflicting with the flowzone package publish.
This commit also adds a new github clean job, to remove any draft
releases left behind after a PR is closed without merging.
> Fix finalization failures on npm/rust/github

- .github/workflows/flowzone.yml
- flowzone.yml
The script now looks for a release before continuing with the finalization steps.
> Fix error in github_finalize if no release exists

- .github/workflows/flowzone.yml
- flowzone.yml
During merge, we want to use the PR source for creating the release notes instead of the latest source since that will include the merge commit and it will pollute the notes.
See https://github.com/balena-os/fatrw/releases/tag/v0.2.14 for an example
> Do not include the merge commit in the release notes

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This will allow testing of the same image that is published by using image: `localhost:5000/sut` in a compose file.
It also ensures only one build and improved caching.
> Combine docker test and publish jobs

- .github/workflows/flowzone.yml
- flowzone.yml
This release removes the deprecated `set-output` command.
Resolves: https://github.com/product-os/flowzone/issues/325
> Update kanga333/json-array-builder to v0.2.1

- .github/workflows/flowzone.yml
- flowzone.yml
This may extend to more valid uses than intended, but for now we need to prevent merging PRs that have had master merged into them. This scenario will break versioning in master.
The intended workflow at balena has always been to rebase PRs, so we have to continue to force this for now and avoid breaking merges.
Resolves: https://github.com/product-os/flowzone/issues/245
> Reject workflow if latest branch commit is a merge commit

- .github/actions/publish/action.yml
- .github/workflows/flowzone.yml
- flowzone.yml
The `github_finalize` job was trying to use the original source of the PR
for creating the release notes. This required the source artifact to
exist at the moment of merge which is not always true as merge can
happen at any point after creating the PR. This changes the job to use
the latest source but exclude the last two commits (merge and version)
from the release notes.
>  Use latest source when creating github release notes

- .github/workflows/flowzone.yml
- flowzone.yml
This prevents docker credentials from leaking into arbitrary test code.
See: https://github.com/product-os/flowzone/issues/332
> Only login to docker registries immediately before pushing

- .github/workflows/flowzone.yml
- flowzone.yml
Do not login to the npm registry if the pull request is an external contribution.
The npm scripts like preinstall and test are considered arbitrary code and cannot be trusted with secrets in the environment.
See: https://github.com/product-os/flowzone/issues/332
> Avoid leaking npm secrets during npm tests

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This toggle can be changed via an input after the custom actions have been vetted for security and cannot leak secrets.
See: https://github.com/product-os/flowzone/issues/332
> Skip custom actions for external contributions by default

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
The test workflow will identify whether the PR is from a fork or not and we can conditionally run either `pull_request` or `pull_request_target` events and skip the other to avoid duplicate workflows.
Modifications to workflow files will be ignored for `pull_request_target` events by GitHub so we just need to make sure we aren't [sharing secrets to the codebase](https://github.com/product-os/flowzone/issues/332).
Depends-on: https://github.com/product-os/flowzone/issues/332
> Allow external contributions

- .github/workflows/flowzone.yml
- flowzone.yml
Using the direct link to refs/pull does not work for merged PRs.
See: https://github.com/product-os/flowzone/pull/346
> Use merge_commit_sha to checkout PR sources

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
Clippy needs to install repository dependencies before running. These dependencies may sometimes require external packages, which are provided by `cross` [pre-build hook](https://github.com/cross-rs/cross#pre-build-hook) feature.
This PR changes the rust steps order so clippy is run using cross instead of default cargo.
> Run clippy using cross for rust targets

- tests/run.sh
We block external contributors when this secret is set so in order to allow contributions to flowzone itself we need to remove the secret and avoid failing the docker compose tests.
See: https://github.com/product-os/flowzone/issues/332, https://github.com/product-os/flowzone/pull/336
> Avoid failing Flowzone self-tests when COMPOSE_VARS is unset

- .github/workflows/flowzone.yml
- flowzone.yml
> Fix refence to merge_commit_sha that was returning empty

- .github/workflows/flowzone.yml
- flowzone.yml
This will break external contributions but will
unblock internal tasks.
> Remove the checkout ref until it can be fixed properly

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This change allows projects like Etcher to be configured to not make every release final, thus avoiding signalling potentially garbage/invalid releases to the world.
It is entirely possible for all Etcher tests to pass with flying colours (green that is) and still not work once installed on one or more platforms. One way to gain more confidence here is to expand Etcher test coverage, implementing proper e2e tests, but we are not there yet.
So, setting `github_prerelease: true` on Etcher repository will create GH releases and enable manual testing to take place before marking a release final/latest.
cc @aethernet @zwhitchcox @mcraa
> Allow GitHub pre-release(s)

- .github/workflows/flowzone.yml
- flowzone.yml
Recently the ubuntu-latest link has started to change from 20.04 to 22.04 and we were caught off guard.
This commit will set the default worker to ubuntu-22.04 unless otherwise specified.
Resolves: https://github.com/product-os/flowzone/issues/397
> Pin the default worker to ubuntu-22.04

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
BalenaCloud docs is the special butterfly that would need this custom website build command to enable it's deployment on Cloudflare Pages using Flowzone. This is a patch until we can actually move the balenaCloud docs to Docusaurus but that will take a long time and this custom way of building websites could potenially be useful to others. 
Things to check
> Add input for custom website build

- .github/workflows/flowzone.yml
- flowzone.yml
Don't `run npm i|ci` when the platform isn't Linux.
(e.g.) https://github.com/balena-io-modules/winusb-driver-generator/blob/master/package.json#L30-L32
> Check package architecture(s)

- .github/workflows/flowzone.yml
- flowzone.yml
Otherwise the entire NPM pipeline is disabled and any assets built in custom workflows can't be published.
> Revert previous

- .github/workflows/flowzone.yml
- flowzone.yml
Allow policy-bot to be matched without the hyphen, and use case-insensitive matching for flowzone, policy-bot, and resinci when modifying the list of required status checks.
> Improve regex for matching required status checks

- .github/workflows/flowzone.yml
- flowzone.yml
The entire download step fails if other artifacts from the workflow run have expired. Make sure we only grab the npm artifacts with the long expiry time.
> Only download the required npm artifacts for finalize

- .github/workflows/flowzone.yml
- flowzone.yml
If we need to re-run a merge job due to a failed publish, we don't want to be blocked by the fact that the commit already exists in the base branch.
> Allow continue on error when pushing versioned commit

- .github/workflows/flowzone.yml
- flowzone.yml
We encountered cases in balena-engine where the tag sorting did not return the expected most recent v tag.
> Update previous tag search to match the v prefix

- .github/workflows/flowzone.yml
- flowzone.yml
See: https://github.com/product-os/flowzone/pull/431
> Fix parsing of previous tag for release notes

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
This check to prevent duplicate runs when both pull_request and pull_request_target are triggered is always required, and is better defined inside Flowzone itself rather than the calling workflow.
> Move workflow de-duplication condition into flowzone core

- .github/workflows/flowzone.yml
- flowzone.yml
From https://github.com/balena-os/meta-balena/actions/runs/3996330198/jobs/6856271201:
```
error: dst refspec 2.107.x matches more than one
error: failed to push some refs to 'https://github.com/balena-os/meta-balena'
Error: Process completed with exit code 1.
```
> Avoid name clashes by specifying branches with heads reference

- .github/workflows/flowzone.yml
- flowzone.yml
This prevents accidentally uploading images that were built with docker-compose tests.
> Save image to file before running compose tests

- .github/workflows/flowzone.yml
- flowzone.yml
This bug prevented the target name from being
prefixed on docker images tags.
> Restore target prefix for non-default targets

- .github/workflows/flowzone.yml
- flowzone.yml
This fixes the `no such file or directory` error when docker compose pre-processing (`docker compose config`) is done for a docker-compose that requires a `.env` file.
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
> Saves the COMPOSE_VARS secret to .env for docker-compose pre-processing.

- .github/workflows/flowzone.yml
- balena.yml
- flowzone.yml
- Add sanitize inputs job
- Rename project_types to process_source
- Rename event_types to check_context
This is the first of a set of commits
to refactor large jobs into smaller components.
This will allow more control over dependencies
while speeding up runtime since more jobs
can run in parallel.
Resolves: https://github.com/product-os/flowzone/issues/108
> Break monolithic jobs into smaller services

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
Adds a `rust_toolchain` (defaults to `stable`) to allow users to configure their preferred toolchain to use when building Rust binaries.
> Make the Rust toolchain version user configurable

- .github/workflows/tests.yml
> Renove balena-cli from e2e tests and re-enable fatrw

- .github/workflows/flowzone.yml
- flowzone.yml
If versioning is disabled and a PR is open, there
will likely not be a tag on the HEAD commit.
However we still want to use something to tag
our artifacts so use git descibe.
> Restore old tag lookup behaviour

- .github/workflows/flowzone.yml
- flowzone.yml
We always want merged PRs to queue up and complete in order or versioning will break.
Resolves: https://github.com/product-os/flowzone/issues/419
> Cancel concurrent jobs with the exception of merged PRs

- .github/workflows/flowzone.yml
- flowzone.yml
Prevent leaking compose secrets during masking due to `-x` shell attribute being set in the `defaults` section.
> Don't leak compose secrets

- .github/workflows/flowzone.yml
- flowzone.yml
For external PRs just use the automatic github actions token
as the scope is already restricted.
> Inject github tokens to docker build and test

- .github/workflows/flowzone.yml
- flowzone.yml
Allow Docker projects to use secrets to access
GITHUB_TOKEN and GH_TOKEN via Dockerfiles.
> Use docker secrets to inject GitHub tokens

- .github/workflows/tests.yml
This should avoid the race conditions where some required checks haven't populated yet, without adding significant time to drafts that are actually complete.
> Require 3 passing loops of required checks for draft PRs

- .github/actions/always/action.yml
- .github/actions/clean/action.yml
- .github/actions/finalize/action.yml
- .github/actions/publish/action.yml
- .github/actions/test/action.yml
- .github/workflows/flowzone.yml
- flowzone.yml
Blocking: https://github.com/balena-io/remote-builders/pull/9
Any concern about custom actions affected in other repos can be easily fixed by pinning flowzone version in workflow.yml, or by updating the custom actions to include the new input.
> Pass vars context to custom*

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
- tests/docker-bake.hcl
This PR requires some adjustments to our self-hosted runner labels.
```json
{
"linux/amd64": ["self-hosted","distro:jammy","platform:linux/amd64"],
"linux/arm64": ["self-hosted","distro:jammy","platform:linux/arm64"],
"linux/arm/v7": ["self-hosted","distro:jammy","platform:linux/arm/v7"]
}
```
Depends-on: https://github.com/product-os/self-hosted-runners/pull/12
> Enable custom runners per docker platform

- .github/workflows/flowzone.yml
- flowzone.yml
Set git release notes on balena releases (e.g.)
https://dashboard.balena-cloud.com/apps/1957201/releases/2455644
Could make it more useful in the future and add a portion of the change log instead of `git tag..tag ..` output.
> Add balena release notes

- .github/workflows/bulk-patch.yml
- BULK-PATCH.md
See: https://github.com/product-os/flowzone/issues/549
This manually triggered workflow removes most of the friction when patching many repositories with the same changes.
- changes must be formatted as patches, and some repos will have merge conflicts, or need a different set of patches
- since this is using the ephemeral GitHub App tokens, a valid installation ID must be provided on each run
```bash
gh workflow run bulk-patch.yml \
--ref "kyle/bulk-pull-requests" \
-f patches_base64="$(cat /tmp/patches.b64)" \
-f repositories="balena-os/balena-raspberrypi" \
-f token_installation_id="34046907" \
-f pr_branch="kyle/bulk-patch" \
-f pr_title="Prevent duplicate Flowzone workflow executions" \
-f pr_body="[skip ci]" \
-f dry_run=false
``` …
> Add a manual workflow to bulk update repositories

- .github/workflows/flowzone.yml
- flowzone.yml
Runners should be ephemeral and these steps just add to build time.
> Remove manual docker cleanup steps

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This is a breaking change for any repositories expecting
image tags in the format `{variant}-{tag}`.
The new default aligns with [docker versioning](https://docs.renovatebot.com/modules/versioning/#docker-versioning).
The old behaviour can be restored with `docker_invert_tags: true`
open-balena-base PR: https://github.com/balena-io-modules/open-balena-base/pull/271
> BREAKING: Change default docker tag format to {tag}-{variant}

- .github/workflows/flowzone.yml
- flowzone.yml
Since we don't rely on Protect Branch as a required check anymore it actually saves time to run it early in the workflow, before jobs like All Tests and All Jobs have queued.
> Run protect branch early in the workflow

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
- tests/docker-bake.hcl
Disabled by default because it's normally not necessary
and creates a lot of extra tags for multiarch images.
> Allow publishing of intermediate docker images

- .github/workflows/flowzone.yml
- flowzone.yml
This seems to be blocking PR close events due to some kind of race condition.
> Disable auto-merge by default

- .github/workflows/e2e.yml
- .github/workflows/flowzone.yml
- flowzone.yml
The automatic GHA token intentionally does not trigger additional actions events, so using it to enable auto-merge causes PR merge events not to trigger any actions.
> Do not use automatic GHA token to enable auto-merge

- .github/workflows/flowzone.yml
- flowzone.yml
GitHub support suggested this should prevent auto-merging without required checks.
> Toggle auto-merge with a reduced scope ephemeral token

- .github/workflows/flowzone.yml
- flowzone.yml
This is a cleanup of the logic to determine which
GH token to provide in different situations.
In all cases we should use the GH app token, or the FLOWZONE_TOKEN, except for user code.
> Use automatic GHA token for steps with user code

- .github/workflows/flowzone.yml
- flowzone.yml
Similar to ts-linter in Python we can use flake8 to lint our code. The problem is that we currently pass the extend-ignore by parameter, which blocks each repo of ignoring its own rules (ideally we want to use all flake8 rules but in reality each repo may sometimes want to ignore particular rules, to do so, one can simply add a flake8 rule to the poetry file or a .flake8 file which will be used)
> Allows each repo to customize extend-ignore rules on python

- .github/workflows/flowzone.yml
- flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/548
See: https://github.com/docker/bake-action/releases/tag/v3.0.0
See: https://slsa.dev/provenance/v0.2
We can re-enable in the future when support is more common.
> Disable SLSA Provenance attestation for now

- .github/workflows/flowzone.yml
- flowzone.yml
This also updates versionist to v6.10.0 to use lockfileVersion 2 with npm-shrinkwrap.json files
Relates-to: product-os/versionist#243
> Update balena-versionist to v0.14.13

- .github/workflows/flowzone.yml
- flowzone.yml
This wraps the shell in the steps that run `npm run test`
and `poetry run pytest` in a `script -q -e -c` to allow tests that
require pseudo-tty (e.g. for applications that work with terminal colors)
to be able to operate as they would in a local dev environment.
> Enable pseudo-tty allocation on test steps

- .github/workflows/flowzone.yml
- flowzone.yml
The `script` command used for pseudo-tty during testing writes to `typescript` in the current directory by default. This may cause issues with some projects that do not expect new files to be generated. This changes the location of that file to the `/tmp` directory to avoid any issues.
> Write `script` output to /tmp

- .github/workflows/flowzone.yml
- flowzone.yml
* CloudFormation step(s) only
..  works by injecting secrets and vars context into the step environment and passing input CFN json through envsubst to resolve the values.
Tested: https://github.com/balena-io/environment-staging/pull/1850
> Inject secrets into environment

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
These commit objects will be automatically signed and verified
if using GitHub app tokens for authentication.
This also removes the need for versioned source artifacts
as each job can clone the versioned commit directly.
> Create versioned commit objects via GitHub API

- .github/workflows/flowzone.yml
- flowzone.yml
If only to make sure we don't apply new branch protections when the commits don't pass the scrutiny of versionist and rebase requirements.
> Make protect branch depend on versioned source

- .github/actions/test/action.yml
- .github/workflows/flowzone.yml
- flowzone.yml
For open pull requests, the versioned commit and tag
objects are created but are intentionally not referenced
anywhere in the git tree.
As such, command line tools like git describe do not return
the current versioned tag which is sometimes used in build scripts.
So before build, test, and publish jobs we can create the references
to the orphaned objects locally. These references should already
exist on merge/finalize.
> Create local refs for orphaned commit and tag objects

- .github/workflows/tests.yml
There are some outstanding issues that should be resolved before enabling this feature anywhere.
> Disable GPT reviews for Flowzone self-tests for now

- .github/workflows/flowzone.yml
- flowzone.yml
This removes a ton of duplicated logic, and encourages use of direct use of the github payload instead of helper functions that may change definitions unintentionally.
> Flatten event types into one job

- .github/workflows/flowzone.yml
- flowzone.yml
Use the PR number for uniqueness when determining concurrency, and only cancel in progress jobs if the PR is open.
> Fix concurrency for external contributions and non-syncronize events

- .github/workflows/flowzone.yml
- flowzone.yml
In the current use cases it doesn't matter if the PR is open or not when performing the steps, and in some cases like configureAWSCredentials we actually expect the PR to be closed sometimes.
> Remove the open condition from external PR checks

- .github/workflows/flowzone.yml
- flowzone.yml
This is to prevent bugs from dependencies from breaking the build.
See: https://github.com/balena-io-modules/node-systemd/actions/runs/5740095381/job/15557192112
Caused by: https://github.com/bytecodealliance/rustix/issues/767
> Use `--locked` flag when installing cross

- .github/workflows/flowzone.yml
- flowzone.yml
We duplicate quite a bit of code in order to support different Python versions. This PR proposes a way to only specify supported versions once (as a variable), and the `is_python` job takes care of everything else.
It relies on the fact that the `setup-python` action supports simultaneous installation of multiple versions (documentation [here](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-multiple-pythonpypy-version)), and then `poetry env use` can be invoked as part of a loop.
Also happens to address #703
> Implement generic Python version compatibility checks

- .github/workflows/flowzone.yml
- flowzone.yml
Fixes a regression where dependencies pick up an array of numbers, causing the annoying 3.10=3.1 bug.
Now the quoted values will always we interpreted as strings.
> Quote validated Python versions

- .github/workflows/flowzone.yml
- flowzone.yml
If custom actions are not allowed, the workflow will be rejected by the custom actions job(s) and fail. With this condition in place it was silently skipping custom actions.
> Always check for the presence of custom actions

- .github/workflows/flowzone.yml
- flowzone.yml
The docker compose tests are one of the few places where we are providing elevated secrets to untrusted user code beyond the workflow itself.
In the case of a GitHub token appended to compose vars, we should use the automatic GHA token if possible and avoid leaking a privileged PAT or ephemeral app token, even when restricted to internal PRs.
See: https://github.com/product-os/self-hosted-runners/pull/75
> Only provide automatic GITHUB_TOKEN to compose vars

- .github/workflows/flowzone.yml
- flowzone.yml
The stable images have been deleted, possibly by mistake, but this is blocking merges.
https://quay.io/repository/containers/skopeo?tab=history
We should install the skopeo binary in our self-hosted images going forward.
> Switch to latest skopeo testing image

- .github/workflows/flowzone.yml
- flowzone.yml
From docker compose documentation:
> The `docker compose run` command is for running "one-off" or "adhoc" tasks. It requires the service name you want to run and only starts containers for services that the running service depends on. Use run to run tests or perform an administrative task such as removing or adding data to a data volume container. The `run` command acts like `docker run -ti` in that it opens an interactive terminal to the container and returns an exit status matching the exit status of the process in the container.
Using `docker compose up` may lead to a false negative test if one of the other services (i.e. not the `sut` service), terminate before the service gets a chance to finish.
> Use `docker compose run` for testing

- .github/actions/always/action.yml
- .github/actions/clean/action.yml
- .github/actions/finalize/action.yml
- .github/actions/publish/action.yml
- .github/actions/test/action.yml
- .github/workflows/flowzone.yml
- .github/workflows/patch.yml
- flowzone.yml
See: https://github.com/product-os/flowzone/pull/743
See: https://github.com/tibdex/github-app-token/releases/tag/v2.0.0
```yaml
installation_retrieval_mode:
description: >-
The mode used to retrieve the installation for which the token will be requested.
One of:
- id: use the installation with the specified ID.
- organization: use an organization installation (https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-organization-installation-for-the-authenticated-app).
- repository: use a repository installation (https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-a-repository-installation-for-the-authenticated-app).
- user: use a user installation (https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-a-user-installation-for- …
```
> Update parameters for tibdex/github-app-token v2

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This applies to all external contributions, not only ones that are using self-hosted runners.
See: https://balena.fibery.io/Work/Task/Replace-run-ci--sha-label-requirement-with-ok-to-test-1353
> Require label 'ok-to-test' for all external contributions

- .github/workflows/flowzone.yml
- flowzone.yml
After discussing https://github.com/cloudflare/wrangler-action/issues/180, it turns out `packageManager` property is supposed to be optional. 
With the new wrangler-action, we no longer need this property.
> patch: Remove packageManager property with wrangler-action 3.3.0

- .github/workflows/flowzone.yml
- flowzone.yml
Allows pushing images to AWS/ECR (e.g.)
* https://github.com/belodetek/cfn-generic-custom-resource/blob/master/.github/workflows/flowzone.yml#L58-L59
* https://github.com/belodetek/cfn-generic-custom-resource/pull/10
> AWS/ECR public/private support

- .github/workflows/flowzone.yml
- flowzone.yml
Don't assume that github.sha is the same as github.ref or even
exists in the clone. Instead fetch and checkout github.ref directly.
> Fetch and checkout merge ref when resetting github directory

- .github/workflows/flowzone.yml
- flowzone.yml
The job would previously look for .tar.gz artifacts which are no longer generated since switching compression
> Look for .zst artifacts when uploading

- .github/workflows/flowzone.yml
- flowzone.yml
These were always a security concern and now there
appears to be no requirement for them.
The workaround for providing GitHub tokens to compose
tests is to encode a PAT as part of COMPOSE_VARS which
are only injected for private repositories.
> Remove GitHub token secrets from docker tests

- .github/workflows/flowzone.yml
- flowzone.yml
This should prevent failing docker compose tests due to a missing env file.
See: docker/compose#10995
> Create empty .env file if no COMPOSE_VARS exist

- .github/workflows/flowzone.yml
- flowzone.yml
Add a postCommand to still have the command output as a GitHub Step Summary as maintainers of wrangler-action setup outputs for this action. 
> Workaround: Pipe Cloudflare command output in Summary

- .github/workflows/flowzone.yml
- flowzone.yml
When running binfmt in a guest docker daemon on arm64 the native support for arm/v6 and arm/v7 is not reflected.
However buildx detects support for those platforms just fine.
> Use buildx as a more reliable check of platform support

- .github/workflows/flowzone.yml
- flowzone.yml
External contributions were using head, the fork, as the repo name when it should have been using the base repo.
> For repo scoped tokens make sure we use the base repo

- .github/actions/publish/action.yml
- .github/workflows/flowzone.yml
- flowzone.yml
Since the release of upload/download artifact v4, artifact names must be unique. As such we must allow additional qualifiers at the end of the artifact name.
> Allow wildcards in the GH release artifact names

- .github/workflows/flowzone.yml
- flowzone.yml
This should avoid failures where compatible python releases are not available on some os/arch combinations but the project is not a python composition anyway.
See: https://github.com/balena-io/environment-production/actions/runs/7278860684/job/19833988183?pr=1902
> Only install python when poetry projects are detected

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
For cases we would like to use self-hosted runners for CF jobs but GitHub hosted runners for supporting jobs.
See: https://github.com/balena-io/environment-production/pull/1903
See: https://balena.zulipchat.com/#narrow/stream/348930-balena-io.2Fflowzone/topic/Prioritize.20environment.20PRs
> Allow custom runners for cloudformation jobs

- .github/workflows/flowzone.yml
- flowzone.yml
Without the new `--admin` flag there should be no chance of accidentally bypassing branch protection rules.
This allows us to use GitHub [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) instead of branch protection and Flowzone doesn't need `admin:read` to verify if there are rules in place.
See: https://cli.github.com/manual/gh_pr_merge
See: https://balena.fibery.io/Work/Improvement/Allow-Flowzone-to-toggle-automerge-without-branch-protection-1529
> Enable automerge regardless of branch protection rules

- .github/workflows/flowzone.yml
- flowzone.yml
This reverts a previous move to tar.zst. While zstd provides better
compression, tar.gz is a more commonly used format and is compatible
accross multiple platforms
This is a major change as it changes the expected output from an
existing process.
> Publish rust binaries in tar.gz format

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
The `custom_runs_on` array supports multiple runner labels in nested arrays.
The new input also allows the use of self-hosted runners as they require multiple labels to identify.
> Remove deprecated tests_run_on input

- .github/workflows/flowzone.yml
- flowzone.yml
We've seen cases where the KVM device is not found on ubuntu-22.04 runners, so continue on error for now.
Failed to open the device 'kvm': No such file or directory
> Ignore KVM setup failure

- .github/workflows/flowzone.yml
- flowzone.yml
See: https://github.com/product-os/flowzone/issues/878
> Use bash to build json arrays and drop unmaintained action

- .github/workflows/flowzone.yml
- flowzone.yml
Npm run docs finalize step has been failing due to lack of relevant permissions. Fixed that to generate docs from `npm run docs` command again. 
Zulip: https://balena.zulipchat.com/#narrow/stream/348930-balena-io.2Fflowzone/topic/Permission.20denied.20when.20running.20npm.20run.20docs
> Add write permission for npm run docs finalize step

- .github/workflows/flowzone.yml
- flowzone.yml
Remove nodejs 12 and 14 versions from the potential nodejs test matrix
as those versions have been EOL for a significant period and continuing to
include them in the potential test matrix provides negligible benefit.
We continue to include nodejs 16 however even though it is also EOL as
of 2023-09-11
Add nodejs 21 as it is the latest version and allows for testing if we support the
latest nodejs version and subsequently whether we are likely to support
the next LTS release out of the box, and if not apply fixes in the
meantime
> Add nodejs 21, remove nodejs 12/14 from the nodejs test matrix

- .github/workflows/flowzone.yml
- flowzone.yml
The motivation for this change was to allow us to properly request the C
Runtime (CRT) to be statically linked.
In summary, each target defaults to either static or dynamic CRT
linking, but we can request static linking regardless of defaults by
using the `crt-static` target feature. The usual way to achieve that is
setting the `RUSTFLAGS="-C target-feature=+crt-static"` environment
variable. (See
https://doc.rust-lang.org/reference/linkage.html#static-and-dynamic-c-runtimes)
Rust projects using Flowzone can already do that by using `cross` for
building and setting the environment variable in a `Cross.toml` file
(see
https://github.com/cross-rs/cross/blob/main/docs/environment_variables.md#environment-variable-passthrough).
So far so good. The problem is, the `--target` option is required …
> Pass the build target when invoking clippy

- .github/workflows/flowzone.yml
- flowzone.yml
There is an issue in v2 of softprops/action-gh-release when providing glob patterns with no matches.
> Filter GH release artifacts before calling release action

- .github/workflows/flowzone.yml
- flowzone.yml
The default behaviour was fixed upstream via
https://github.com/softprops/action-gh-release/pull/425/commits/f4bd9669044d0fa04ba1b4b0785e05e2b6055d66
> Do not fail releases on unmatched files

- .github/workflows/flowzone.yml
- flowzone.yml
* https://github.com/actions/setup-python/issues/705
* https://github.com/balena-io/environment-production/actions/runs/8423822603/job/23066477310?pr=2178#step:8:24
> run steps on X64 only

- .github/workflows/flowzone.yml
- flowzone.yml
* installing Python dependencies on runner [breaks](https://github.com/balena-io/environment-playground/actions/runs/8425936303/job/23073177694?pr=62#step:13:38) other dependencies (e.g. AWS-CLI)
> revert product-os/flowzone/pull/953

- .github/workflows/flowzone.yml
- flowzone.yml
Without this dependency, we were cloning the default
sha in the checkoutVersionedSha sha step. It was a coincidence
that this worked for internal PRs.
It became obvious when I saw the step in the workflow reported
as "Checkout" instead of "Checkout abc123..."
> Fix missing dependency on versioned source

- .github/workflows/flowzone.yml
- flowzone.yml
By setting up the publish matrix ahead of time with
the expected platforms, slugs, etc. we can process each
artifact by name rather than glob matching.
> Verify that all required docker artifacts exist

- .github/workflows/flowzone.yml
- .husky/pre-commit
- README.md
- flowzone.yml
- package.json
Alternative to https://github.com/product-os/flowzone/pull/968 in order to combine actionlint with pre-commit hooks.
Repositories with workflows containing linting errors will fail the check and see annotations in the changed files tab.
For now shellcheck linting has been disabled, and will be enabled in a future PR.
> Lint with all workflows with actionlint

- .github/actions/publish/action.yml
- .github/workflows/flowzone.yml
- flowzone.yml
These artifacts only need to exist until the next
job in the current workflow run, and have no need
for uniqeness as they are already tied to the run
of the workflow.
> Remove git hash from ephemeral artifact names

- .github/workflows/flowzone.yml
- flowzone.yml
Otherwise we get errors when using labels like "vm" or "actuated".
See: https://github.com/balena-io/e2e/actions/runs/8649345888/job/23715409080?pr=647
> Ignore custom runner labels in actionlint

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
uses Renovate's release notes from the PR description (e.g.) throw-away/superseded PR
* https://github.com/balena-io/balena-cloud/pull/2907#issuecomment-2073662535
* Zulip messages (on merge) remain to be tested, but *should* work
.. duplicates need to be fixed [upstream](https://github.com/renovatebot/renovate/issues/13037)
> adds release notes into PR as a comment

- .github/workflows/flowzone.yml
- flowzone.yml
When the github url was moved into the yaml env var declarations the $GH_REPO env var substitution that was previously being handled by bash is no longer being performed which means the incorrect url is being used to attempt the update. This change switches to the gh action interpolation for the repository which will restore the url to its previous state.
> Fix version bump on merging

- .github/workflows/flowzone.yml
- flowzone.yml
A previous change introduced an error where we started passing the commit object sha when creating the tag reference.
The result appears to pass but creates a tag of type commit and is not an annotated tag.
See: https://github.com/balena-os/balena-yocto-scripts/pull/339
> Fix passing of tag object commit when creating reference

- .github/workflows/tests.yml
The smallest hosted runners use those specs, and
anything smaller might be unreliable.
> Increase base actuated runner size to 2cpu 8gb

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
Allow controlling the number of parallel matrix
jobs via an input, defaulting to 8.
> Set max parallel value for all matrix jobs

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
According to the team at Actuated, and observed in our job queue, setting a max parallel matrix value DOES NOT prevent a runner from being assigned to the job. It takes the runner but is prevented from executing the steps if the max value is reached.
So for now we will set the default max parallel jobs to the same global 20 concurrent max in our Actuated plan.
This will prevent jobs from taking a runner slot only to be stopped from execution by the GH max parallel setting.
> Increase default max parallel matrix jobs to 20

- .github/workflows/flowzone.yml
- flowzone.yml
* otherwise on every PR sync, manually edited release notes will be lost
> don't clobber edited comments

- .github/workflows/flowzone.yml
- flowzone.yml
..  check if `find_edited_comment` step resolves to a blank string before sending a Zulip message; if the placeholder text has been removed this step evaluates to `''`. 
fixes: https://github.com/balena-io/environment-production/actions/runs/9036814183/job/24834604257
> check if the comment has been edited before sending msg

- .github/workflows/flowzone.yml
- flowzone.yml
Look for a `## Release notes` section on the PR body and append the contents of the section to the release notes in GitHub and balenaCloud.
Flowzone will now look for a `## Release notes` section on the PR body. When defined, it will use the contents of that section and the PR title for the automatically [generated release notes in GitHub](https://github.com/product-os/flowzone/releases/tag/v11.4.10). If the repository is identified as a [Balena project](https://github.com/product-os/flowzone?tab=readme-ov-file#balena), it will also use the user provided release notes to populate the Balena release notes.
If no `Release notes` section is defined, the workflow will just use the Git change-log, unless the `release_notes` option is set to `false`.
> Use PR body to build GitHub/Balena release notes

- .github/workflows/flowzone.yml
- flowzone.yml
.. this should match for the string `* [only keep the important and rephrase]` anywhere in the release notes text, without being tripped up by new lines, etc. (or if more whitespace is added by accident).
(string to match)
https://github.com/balena-io/environment-production/actions/runs/9082537944/job/24959245850#step:5:46
(aggressive regex)
https://github.com/balena-io/environment-production/actions/runs/9082537944/job/24959245850#step:5:133
(wrong, should be found)
https://github.com/balena-io/environment-production/actions/runs/9082537944/job/24959245850#step:5:138
.. suspect `\n` at the end is the cause.
> relax regex to match anywhere

- .github/workflows/flowzone.yml
- flowzone.yml
The renovate release notes were being overwritten by the default non-renovate behavior.
This updates the code to handle both cases exclusively.
> Fix renovate release notes

- .github/workflows/flowzone.yml
- flowzone.yml
The 'Notable changes' section was being formatted differently on the GitHub release notes and the Zulip message.
> Reuse notable changes format on release notes

- .github/workflows/flowzone.yml
- flowzone.yml
A bug in the previous version was ignoring the contents inside the summary tag. This also adds indentation to second level changes (starting with a `> -`) and removes duplicate lines.
> Improve notable changes generation

- .github/workflows/flowzone.yml
- flowzone.yml
For the release notes comment, this restores the re-itemization of the notable changes list with `*`, to make it clear that the lines should be edited.
> Restore re-itemization of notable changes

- .github/workflows/flowzone.yml
- flowzone.yml
Historically we have used the PR merge commit, which is the GitHub default, to ensure that we are testing the same merges that will be committed to the target branch.
However, we already require that branches be rebased on the target before merging via branch protections so there is no benefit gained from using the merge commit.
We also would like to enable use cases where we are testing against old versions of the target branch and not include changes from the tip of the target.
See: https://balena.zulipchat.com/#narrow/stream/348930-balena-io.2Fflowzone/topic/Flowzone.20runs.20tests.20w.2F.20merge.20w.2F.20master/near/438995412
See: https://balena.fibery.io/Work/Project/Base-Flowzone-versioned-commit-on-the-tip-of-the-PR-head-537
> Base versioned commit on the tip of the PR head branch

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- flowzone.yml
We've seen cases where the checkout ref was undefined because a step with the output wasn't run, or because of unexpected results in the github context json.
Without this change, the checkout would continue but quietly fallback to the ref or sha for the event with unexpected results.
With this change, the checkout will fail so we can fix the workflow.
> Fallback to an invalid ref if the checkout ref is undefined

- .github/workflows/flowzone.yml
- flowzone.yml
The extra indentation for the second level changes is lost in the release notes comment, so this restores the previous formatting only for the comment.
The general release notes will look the same.
> Restore MD quote for second level changes

- .github/workflows/flowzone.yml
- flowzone.yml
The work on PR #1046 made the finalize github release job dependent on the `release_notes` input. That's a regression on the correct behavior. This PR moves the PR comment and deploy message actions to a separate job that is dependent on the release notes input, and makes the release_notes job run on every PR, which allows the github finalize job to always run on merge.
This is a major change because it changes the way the release_notes input work, even though it restores the right behavior.
This release fixes a regression that prevented finalizing the GitHub release unless the `release_comment` input was set to true. This restores the correct behavior, however it is a major change as it is changing an interface (even if the interface was bad).
> Fix regression on the GitHub finalize job

- .github/workflows/flowzone.yml
- flowzone.yml
Node 21 is going EOL on 01 Jun 2024.
Not marking node 22 as the default yet,
since it's not yet LTS.
See: https://endoflife.date/nodejs
> Replace almost-EOL node 21 with node 22 (current)

- .github/workflows/flowzone.yml
- flowzone.yml
* otherwise Cloudformation updates won't run on base digest merges (e.g.)
https://github.com/balena-io/environment-production/pull/2421
> look for changed files in submodules

- .github/workflows/flowzone.yml
- flowzone.yml
Increase cache from min to max, and remove the branch
name from the cache scope.
Max mode will cache all layers, including intermediate stages.
This is a minor change as some repositories may run out
of cache space when building for many platforms.
See: https://docs.docker.com/build/cache/backends/gha/
> Improve caching of docker builds

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
**Remove deprecated input job_name**
The functionality behind this input was removed
when we stopped patching branch protections.
**Remove deprecated custom_environments input**
This property was only used in one repository for testing
> Remove some deprecated inputs

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This should automatically generate an sbom for nodejs projects using cyclonedx and add upload it to the assets.
Once this works, the next step will be to publish it to a central dependency-track server.
> minor: generate sbom for node/npm, python/poetry and rust/cargo projects

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
SBOM generation is failing for some repository with some specific configuration.
This PR adds a global flowzone parameter to turn off sbom generation (on by default) and will `continue-on-error`.
> patch: add an option to not generate sbom

- .github/workflows/flowzone.yml
- flowzone.yml
It's annoying to find the CF pages link from inside the GHA run summary, lost of people have had this friction. 
No more. This PR adds that link to the comments. 
Zulip: Started from https://balena.zulipchat.com/#narrow/stream/408336-aspect.2Fuser-experience/topic/Where.20should.20SAML.20docs.20fit.20in.3F
> Add Cloudflare Pages link as PR comment

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
This should reduce our fetch depth in almost all cases
while still including commits required for versioning
and changelogs and release notes.
Reducing fetch depth saves a lot of time on the checkout
step present in most jobs, so every little bit helps.
> Use calculated fetch depth for versioned source checkout

- .github/workflows/flowzone.yml
- flowzone.yml
When node version is not specified by a job,
use 20.x instead of 18.x
> Update default node version to 20.x

- .github/workflows/flowzone.yml
- flowzone.yml
There is a bug in Node 22.5.0 that is affecting NPM workflows. This is a temporary fix until that issue closes.
Relates-to: npm/cli#7657
> Pin Node 22 minor version to 22.4

- .github/workflows/flowzone.yml
- flowzone.yml
My usecase for this output is to get it from Flowzone and give it to the link checker running in Docs to check links for the staging docs in order to make sure we are not breaking links on a per PR basis. 
(Pain driven development: I broke a link on a previous PR and link-checker didn't find out)
> Output Cloudflare Deployment URL 

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
Default to a fetch depth of 1 unless overridden via the input. Always use fetch depth of 0 when release notes are being calculated.
Some balenaOS repositories have submodules that require a fetch depth of 1700+ in order to get the pinned commit. Those repos need to be able to override the default of 1.
> Checkout versioned source with full depth for release notes

- .github/actions/test/action.yml
- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This also requires manually fetching all tags for
jobs that generate release notes.
> Use a checkout depth of 100 when no submodules exist

- .github/workflows/flowzone.yml
- flowzone.yml
This job is used for branch requirements, and
we don't want it to show as skipped in case the PR is ever reopened.
See: https://github.com/product-os/flowzone/issues/1143
> Mark All jobs as failed on PR closed events

- .github/workflows/flowzone.yml
- flowzone.yml
Tested [here](https://github.com/balena-io/environment-staging/actions/runs/10409345156/job/28831503909#step:16:52)
There needs to be an additional step when packaging CFN tempates containing Lambda/Code: reference directory. By default, without using a completely different CFN "SAML" workflow (we don't want to go there maybe yet), dependencies need to be installed into the same directory as the Lamda code.
This comit implements this workflow for Python code when requirements.txt is present.
> CloudFormation package does not install Lambda deps.

- .github/workflows/flowzone.yml
- flowzone.yml
`AWS::Lambda::Function(s)` can have different code syntax
(1) point to a directory to be packaged manually
```
LambdaFunction:
Type: AWS::Lambda::Function
Properties:
Code: lambda/
Handler: handler.lambda_handler
```
(2) inline
```
BackupCopyManagerLambda:
Type: AWS::Lambda::Function
Properties:
Handler: index.lambda_handler
Code:
ZipFile: |
import time, json, boto3, os, sys, logging, urllib3
COPY_TO_ACCOUNT_TAG = os.environ.get('COPY_TO_ACCOUNT_TAG')
...
```
This patch should handle both cases (currently it only handles 1).
> Check if Code does in fact point to a valid directory

- .github/workflows/flowzone.yml
- flowzone.yml
We have a step to manually fetch tags when depth is not 0, but this step has been broken since we disabled persisting of credentials from the checkout step.
See: https://github.com/product-os/flowzone/pull/1187
> Force full fetch depth in order to retrieve all tags

- .github/workflows/flowzone.yml
- flowzone.yml
In a [previous change](https://github.com/product-os/flowzone/pull/1187) we disabled persistence of auth following the actions/checkout step.
This PR is to manually provide temporary auth to `git fetch` steps that were relying on the existing auth before.
> Provide temporary credentials when performing git fetch

- .github/workflows/flowzone.yml
- flowzone.yml
Expressions in the concurrency context do not have access
to the github.event context so we cannot make advanced
expressions beyond a few top level github event fields.
See: https://github.com/orgs/community/discussions/69704#discussioncomment-7803351
> Fix concurrency cancel-in-progress conditions

- .github/workflows/flowzone.yml
- flowzone.yml
This prevents merging PRs that do not have any required checks, in theory. In practice the rules may not contain required status checks but the presence of any branch rule is good enough.
> Only toggle auto-merge if base branch has protection rules

- flowzone.yml
The sha based dist-tag is minimally useful as you can install the version directly since the sha based dist-tag will be unique to a specific version anyway whereas the branch based dist-tag can be used as a floating tag to automatically follow the latest build of the branch if desired
> Only add a branch based npm dist-tag, not sha based

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
The existing method of using labels allows for
Actions Time Of Check to Time Of Use (TOCTOU) attacks because we do not associate the label with any commit.
This action requires approvals via reactions on a unique comment for every workflow run.
See: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
See: https://balena.fibery.io/Work/Improvement/Require-approvals-for-pull_request_target-triggers-in-Flowzone-2260
See: https://github.com/product-os/review-commit-action
> Wait for approvals on pull_request_target events

- .github/workflows/flowzone.yml
- flowzone.yml
- tests/Cargo.toml
The cargo_finalize step publishes to the configured registry if CARGO_REGISTRY_TOKEN is set, but this step will fail if `publish` is set to false in Cargo.toml. This disables the step in that case to prevent an error.
> Do not run cargo publish if disabled in Cargo.toml

- .github/workflows/flowzone.yml
- flowzone.yml
On PRs from forks the approval action was lacking
permission to create comments.
> Add missing permissions to create PR comments

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- flowzone.yml
Posting a comment to a PR does not require the elevated access of the flowzone-app[bot] so we can just go back to using the automatic github token with hardcoded permissions as we were before.
> Revert to automatic github token for website comments

- .github/actions/always/action.yml
- .github/actions/clean/action.yml
- .github/actions/finalize/action.yml
- .github/actions/test/action.yml
- .github/renovate.json
- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This allows us to fail the step as expected if an App ID is provided but we are unable to generate a token. Otherwise it is very hard to find the issue in the logs.
> Only generate installation tokens when App ID is provided

- .github/workflows/flowzone.yml
- flowzone.yml
We are now using an app installation token for the workflow approval action, and this token expires after 1h.
Note that the job can still be re-run and the approval will be requested again.
See: https://balena.fibery.io/Work/Improvement/Define-explicit-permissions-in-Flowzone-for-GITHUB_TOKEN-2307
> Set a 60 min timeout for event_types jobs

- .github/workflows/flowzone.yml
- .gitignore
- flowzone.yml
The previous behaviour was allowing merged PRs to
run at the same time because the head_refs would differ.
See: https://balena.zulipchat.com/#narrow/channel/348930-balena-io.2Fflowzone/topic/versioned.20tag.20different.20commit.20than.20master/near/483065263
> Fix merged PRs to share a single concurrency group

- .github/workflows/tests.yml
The default read-only policy does not provide any discussion permissions, so we should update this test workflow to remain aligned for clarity.
See: https://balena.fibery.io/Work/Improvement/Define-explicit-permissions-in-Flowzone-for-GITHUB_TOKEN-2307
> Fix a typo in the test workflow providing discussion: read access

- .github/workflows/flowzone.yml
- flowzone.yml
See: https://balena.fibery.io/Work/Improvement/Run-octoscan-as-part-of-Flowzone-workflows-2384
See: https://balena.zulipchat.com/#narrow/channel/345885-aspect.2Fsecurity/topic/Penetration.20Testing.20of.20balenas.20CI.2FCD/near/482670470
I've opened a feature request for inline ignore directives: https://github.com/synacktiv/octoscan/issues/16
> Run octoscan as part of Flowzone workflows

- .github/workflows/flowzone.yml
- flowzone.yml
Private repositories seem to not have the required permissions for upload.
See: https://balena.fibery.io/Work/Improvement/Run-octoscan-as-part-of-Flowzone-workflows-2384
See: https://github.com/github/codeql-action?tab=readme-ov-file#workflow-permissions
> Ignore failures to upload SARIF file for private repos

- .github/workflows/flowzone.yml
- flowzone.yml
It is unclear why most of our public repos do
not fail this step, as expected. Add this condition for those that do, and private repos.
> Ignore SARIF file upload failures from octoscan

- .github/workflows/flowzone.yml
- flowzone.yml
Use the GitHub API to check commit parents in BASE and HEAD
branches and ensure we are following a linear history.
HEAD should not have any merge commits, so reject any HEAD branches
where one or more commits have multiple parents.
The PR merge commit must include the HEAD commit as a parent,
otherwise reject the versioning job.
> Improve enforcement of linear commit history

- .github/workflows/flowzone.yml
- flowzone.yml
The default permissions do not always include pull_request:read
> Use app installation token to validate linear history

- .github/workflows/flowzone.yml
- flowzone.yml
See: https://github.com/docker/buildx/releases/tag/v0.19.2
```
#1 [internal] load local bake definitions
#1 reading /home/runner/work/_temp/docker-bake.json 342B / 342B done
#1 reading /home/runner/work/_temp/docker-actions-toolkit-DGkl1b/docker-metadata-action-bake.json 1.89kB / 1.89kB done
#1 DONE 0.0s
ERROR: EOF
Error: cannot parse bake definitions: ERROR: EOF
```
> Pin buildx to v0.19.1 to fix broken bake definiton parsing

- .github/renovate.json
- flowzone.yml
Manager preset is copied from here:
https://docs.renovatebot.com/presets-customManagers/#custommanagersgithubactionsversions
Without this change Renovate was not discovering any of the `# renovate` regex in `flowzone.yml`
> Add top-level flowzone.yml to custom regex manager

- .github/renovate.json
Whether the manager is github-actions or regex, we still need to re-generate .github/workflows/flowzone.yml if ./flowzone.yml has changed.
> Add regex manager to commit hooks package rule

- .github/workflows/flowzone.yml
- flowzone.yml
The security-events permission is not granted by the restricted
automatic token policy so in order for this to run at scale we
need to use app installation tokens.
The codeql-action/upload-sarif action using internal endpoints
and does not work with app installation tokens so here we use
the github-script action to upload the SARIF file to GitHub via
the REST API.
See: https://github.com/github/codeql-action/issues/2654
> Use app installation tokens to upload octoscan SARIF

- .github/workflows/flowzone.yml
- flowzone.yml
Resolves 10 code-scanning warnings.
> Use github-script to generate versioned blobs and commits

- .github/workflows/flowzone.yml
- flowzone.yml
Parsing the tree JSON will break the workflow
if versioning is disabled and the JSON is null.
Add a new 'sha' output in addition to the entire
tree returned object.
See: https://github.com/klutchell/dnscrypt-proxy-docker/actions/runs/12636875719/job/35209949431?pr=511
> Add tree sha to create_tree outputs

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
This is the new default "ubuntu-latest" tag provided by GitHub starting in Dec 2024.
See: https://github.com/actions/runner-images/issues/10636
> Pin helper jobs to ubuntu-24.04 runners by default

- .github/workflows/flowzone.yml
- flowzone.yml
The octoscan commit that added this check was clear that it needs some improved regex.
As it stands it will flag any writes to GITHUB_ENV or GITHUB_OUTPUT whether they are being used
unsafely in a following step or not.
For now let's disable it to get past all the noise until octoscan can correctly identify improper usage.
Reduces our code scanning alerts from 162 to 73 ([see here](https://github.com/product-os/flowzone/security/code-scanning?query=is%3Aopen+pr%3A1316)).
> Add dangerous-write to octoscan ignore list

- tests/package.json
This reverts commit 441c9e81fa5e562870de346b1dc16e0b00e1a124.
This commit was only for testing, but the PR was merged by mistake when I didn't mark it as draft.
> Revert "Test with unsupported node version (should use 20.x)"

- .github/renovate.json
- .github/workflows/flowzone.yml
- flowzone.yml
This prevents drift of node versions in the tool cache between main and development branches.
Dry-run here for testing Renovate: https://github.com/product-os/.github/pull/118
> Use Renovate to pin to latest LTS node releases

- .github/workflows/flowzone.yml
- flowzone.yml
There is no value in running actionlint or pre-commit checks
on PR merge or close events.
Same with the Node version checks, no need on close events.
The octoscan checks should run on merge to update the main
branch code scanning results, but not on PR close.
Tested close event [here](https://github.com/product-os/flowzone/actions/runs/12817468822).
Note that `File List` runs without failing, so we can leverage it for `Custom always` job conditions in a future PR.
These jobs do not rely on versioned source, so they
can default to the pull request HEAD sha and fallback
to the github ref for other event types.
Using the github ref is not appropriate for pull_request_target
events where the ref/sha is always the base branch.
> Prevent linting jobs from running on PR close events

- .github/workflows/flowzone.yml
- flowzone.yml
This uses the GitHub API to get previous tags
and commit messages, while avoiding issues due to
extremely long strings and special characters.
This also means we don't need to clone the repo
with the last n tags in order to generate release
notes so we can change the default checkout depth
in a future PR.
This PR also fixes the run conditions for release_notes
to ensure we skip those jobs on repos with versioning disabled.
Example release from this PR: https://github.com/product-os/flowzone/releases/tag/untagged-71d2fb3c1318e8ec115d
Use the GitHub API to get previous tags
and commit messages, while avoiding issues due to
extremely long strings and special characters.
> Use github-script to generate release notes

- .github/workflows/flowzone.yml
- flowzone.yml
The release_notes input is meant to control
whether we take special balena-specific steps
to publish release notes to internal message boards.
It is NOT a flag to disable or enable creating releases.
Fixes: https://github.com/product-os/flowzone/pull/1332/commits/16edbed9baf703844f47a54e81e9a982f2e096dd
> Restore previous conditions for release_notes

- .github/workflows/flowzone.yml
- flowzone.yml
Using node over jq+shell is cleaner and less likely to cause weird behaviour with an undetected typo.
Using file_list also allows us to skip the job entirely when certain files do not exist.
> Refactor is_docker to use file_list and github-script

- .github/workflows/flowzone.yml
- flowzone.yml
On merge events, the new tag was being captured
as the previous and no commits were included in
the changelog.
Fixes: https://github.com/product-os/flowzone/pull/1332
> Filter the current tag for merge events

- .github/workflows/flowzone.yml
- flowzone.yml
Prior to the last change, we only ran docker build+test jobs if there were images to publish, or compose files to test.
Restore that behaviour to avoid running docker bake for repos only meant to publish to balena.
The previous conditions can be seen here:
https://github.com/product-os/flowzone/blob/e2e14f913b98332cb25a2ec1c26ee1343946e263/flowzone.yml#L2123-L2125
> Restore docker build+test conditions

- .github/workflows/flowzone.yml
- flowzone.yml
This avoids artifact download failures when the node version changes between draft and merge.
> Remove node version from artifact names

- .github/workflows/flowzone.yml
- flowzone.yml
Using regex to download artifacts caused the artifact to be downloaded into a subdirectory causing issues with the publish step.
> Extract npm and docs artifact from subdirectory

- .github/workflows/flowzone.yml
- flowzone.yml
The bug introduced in v0.10.0 has been fixed in [v0.20.1](https://github.com/docker/buildx/releases/tag/v0.20.1).
See: https://github.com/docker/buildx/issues/2859
See: https://github.com/docker/buildx/pull/2863
> Align buildx versions to v0.20.1 for default target fix

- .github/workflows/flowzone.yml
- flowzone.yml
ARMv6 builds may hang when building on ARMv8 hardware due to emulated CP15 builds. This configures the runner kernel to use hardware execution rather than emulation to avoid the issue.
> Use hw execution for cp15 barrier instructions

- .github/workflows/flowzone.yml
- flowzone.yml
The [last change](https://github.com/product-os/flowzone/pull/1364) to the labels metadata broke conditions when there was a tag prefix or suffix and we were expecting to test "sut:latest" via the compose file.
We were only creating local tags with the format "sut:prefix-latest" or "sut:latest-suffix" so docker compose couldn't find the expected "sut:latest" tag and would rebuild, possibly with the wrong targets.
See: https://github.com/product-os/flowzone/pull/1364
> Restore the "sut:latest" tag for local compose tests

- .github/workflows/flowzone.yml
- README.md
- flowzone.yml
Now that [we are using rulesets across all orgs](https://balena.fibery.io/Work/Project/Switch-to-rulesets-for-branch-protection-via-safe-settings-304) we can add the Flowzone GitHub App to the ruleset exceptions and no longer require `admin:write` permissions to push directly to main branches.
See: https://balena.fibery.io/Work/Project/Switch-to-rulesets-for-branch-protection-via-safe-settings-304
See: https://balena.fibery.io/Work/Improvement/Remove-admin-write-permissions-from-flowzone-app-1389
Merge tested here: https://github.com/balena-io-experimental/flowzone/actions/runs/13550595477/job/37873044837
Legacy protection check tested here: https://github.com/balena-io-experimental/flowzone/actions/runs/13553653908/job/37883000879?pr=15
> Remove admin:write from versioning steps

- .github/workflows/flowzone.yml
- .github/workflows/tests.yml
- README.md
- flowzone.yml
Now that GitHub offers free hosted runners in both architectures we should default to these in Flowzone.
See https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Github-Actions-are-not-picked-up-by-self-hosted-github-runners-68
> Use hosted Ubuntu 24.04 X64 and ARM runners for Docker by default

- .github/actions/test/action.yml
- .github/workflows/flowzone.yml
- flowzone.yml
This includes large runners we may provision during
outages of self-hosted runners.
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Github-Actions-are-not-picked-up-by-self-hosted-github-runners-68
> Check KVM support on any X64 Linux runner

- flowzone.yml
This allows Renovate to separate the PRs by major/minor/patch revisions instead of just treating them all as digest updates.
> Use full semver to pin actions/github-script

- .github/workflows/flowzone.yml
- flowzone.yml
Unhandled error: TypeError: Cannot read properties of null (reading '1')
> Catch unhandled type errors when release notes are not matched

- .github/workflows/flowzone.yml
- flowzone.yml
Tag push events are only somewhat supported, and there is no situation where this ever would have worked since we need to look at the PR body and commits to generate notes.
Tag push logs:
> Remove tag push events from release notes generation

- .github/workflows/flowzone.yml
- flowzone.yml
The job step was encoding as JSON, resulting in additional escaped characters when publishing the notes to balenaCloud.
See this as an example https://dashboard.balena-cloud.com/apps/1667443/releases/3416828/summary
Fixes release notes being encoded as JSON which was affecting the preview of the balenaCloud release
> Encode short-release-notes as string

- .github/workflows/flowzone.yml
- flowzone.yml
The previous tag may not exist on new projects, so just list the new commits compared to the base ref.
See: https://github.com/balena-io-experimental/balenamcp/actions/runs/15216921797/job/42804496842?pr=1
> Fallback to the base ref if the previous tag cannot be found

- .github/workflows/flowzone.yml
- flowzone.yml
We want to avoid superfluous source checkouts and instead rely on the sanitized versioned source artifact.
This also applies to a future state where versioning is performed externally by a dedicated app, and the job(s) checkout the versioned commit branch.
See: https://balena.fibery.io/Work/Project/Make-Flowzone-secrets-conditional-1398
> Replace shallow checkouts with versioned source artifact

- .github/workflows/flowzone.yml
- flowzone.yml
> our version is very old
Required by: https://github.com/balena-io/environment-staging/pull/5983
> patch: Update CFN linter

- .github/workflows/flowzone.yml
- flowzone.yml
For large repos, this can result in files that are hundreds of megabytes.
Instead, perform a new checkout of the versioned source commit with the minimum fetch depth required.
> Avoid full fetch depth for versioned source artifacts

- .github/workflows/flowzone.yml
- flowzone.yml
There may be multiple sections in Cargo.toml including `name =` which will metadata generation to [fail](https://github.com/balena-io-experimental/helios/actions/runs/16228039292/job/45824579468). This channge updates parsing of Cargo.toml to read only the first instance of `name` assuming that will belong to the `package` section.
> Use only first occurrence of `name = *` in Cargo.toml

- .github/workflows/flowzone.yml
- flowzone.yml
Not all projects that publish websites are node/npm projects, and we don't actually require package.json files to set the max node version output.
See https://github.com/product-os/flowzone/commit/b40d021005b7d4e774d2ef6c09a8cbe71c958007
> Remove npm requirement from website publish

- .github/renovate.json
See: https://github.com/docker/buildx/issues/3328
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Failing-Run-docker-compose-tests-CI-check-108
> Disable renovate bumps to buildx v0.26.0

- .github/workflows/flowzone.yml
- flowzone.yml
This also brings npm 11 for faster installs. Any steps that require an older nodejs version should be explicit about that dependency
> Switch to nodejs 24 as the default for node steps

- .github/workflows/flowzone.yml
- flowzone.yml
This is required for nested changelogs and was broken when we moved to the new token action.
Fixes failures like [this](https://github.com/balena-io/remote-workers/actions/runs/18283532064/job/52054952709?pr=280)
> Update versionist token to include all repos in org
