product-os/flowzone

.github/workflows/flowzone.yml, .github/workflows/test.yml
=> patch: Set versionbot to checkout the base_ref

.github/actions/versionbot/action.yml, .github/workflows/flowzone.yml, .github/workflows/test.yml
=> patch: Run versionbot on push to main branch

.github/workflows/flowzone.yml
=> patch: Fix conditions for running versionbot

.github/actions/versionbot/action.yml, .github/workflows/flowzone.yml
=> patch: Checkout source before calling local composite actions

README.md
=> Add resinCI migration instructions

.github/workflows/flowzone.yml, README.md
=> Require Flowzone tests

.github/actions/docker/action.yml, .github/actions/npm/action.yml, .github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md, tests/docker-compose.test.yml
=> Extend docker flow to support multiarch and pushing to registries

.github/actions/versionbot/action.yml, .github/workflows/flowzone.yml
=> patch: Change the versionbot author to Flowzone

.github/actions/versionbot/action.yml, .github/workflows/flowzone.yml
=> patch: Remove references to versionbot

.github/actions/versionist/action.yml, .github/workflows/flowzone.yml
* remove redundant quotes
* begin comments with lowercase
* correct branding /nomenclature
=> Checkout prior to running actions

.github/actions/protect-branch/action.yml, .github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/19
=> Add deploy-to-balena action

.github/workflows/flowzone.yml, .github/workflows/tests.yml
=> Add versioned source flow to merge versionbot branch to main

.github/workflows/flowzone.yml
=> Fix versioned source extraction on merge

.github/workflows/flowzone.yml
=> Rebase versioned source before pushing to main

.github/workflows/flowzone.yml
=> Cherry-pick the versioned commit to main so we can gpg-sign

.github/workflows/flowzone.yml, .github/workflows/tests.yml, tests/Dockerfile
=> Split docker builds into a matrix of platforms

README.md
=> patch: Update examples in readme

.github/workflows/flowzone.yml
=> Split versioned source job into 3 smaller jobs

.github/workflows/flowzone.yml
=> Create docker manifest after individual platforms

.github/workflows/flowzone.yml, .github/workflows/tests.yml, tests/balena.yml
=> Push multiple architecture-specific balena releases by default

.github/workflows/flowzone.yml
=> patch: Re-upload the versioned source artifact under a versioned name

.github/workflows/flowzone.yml
=> patch: Use tip of pull request branch to name artifacts

.github/workflows/flowzone.yml
=> Use last commmit from head of the PR branch for artifact tags

.github/workflows/flowzone.yml
=> Finalize docker images on merge events

.github/workflows/flowzone.yml
=> Login to container registries for finalize

.github/workflows/flowzone.yml
=> patch: Finalize balena releases on merge

.github/workflows/flowzone.yml
=> Refactor docker repositories into just ghcr.io and docker.io

.github/workflows/flowzone.yml, README.md
=> Update documentation for the supported project types

.github/workflows/flowzone.yml, README.md
See: https://github.com/product-os/flowzone/issues/59
=> Only finalize artifacts on merge if versionbot is in use

.github/workflows/flowzone.yml
=> patch: Fix check for versionbot author

.github/workflows/flowzone.yml, .github/workflows/tests.yml
Just to confirm that tags are ignored when versionbot is enabled.
=> Enable tag events for this repo only

.github/workflows/flowzone.yml, README.md
=> Fix protect branch run conditions

.github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/60
=> Assert that versioned source is up-to-date

README.md
=> patch: Fix inputs example in readme

README.md
Resolves: https://github.com/product-os/flowzone/issues/77
=> Demonstrate that secrets can only be inherited in some cases

.github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/83
=> patch: Only extract version info if author is versionbot

.github/workflows/flowzone.yml
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
=> Run versionist if versiobot branch for PR does not exist.

.github/workflows/flowzone.yml
=> Rename NPM to npm to match the official product name

.github/workflows/flowzone.yml, README.md
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
=> Do versioning on PR branch.

.github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/93
=> Determine the highest version in all versioned files

.github/workflows/flowzone.yml
=> patch: Require full fetch depth for versionist

.github/workflows/flowzone.yml, .github/workflows/tests.yml
=> Combine docker merge and tagged steps

.github/workflows/flowzone.yml
=> Combine npm draft and npm final steps

.github/workflows/flowzone.yml
=> Merge docker draft and docker finalize jobs

.github/workflows/flowzone.yml
=> Fix missing dependency on versioned source for docker publish

.github/workflows/flowzone.yml
=> Protect branch depends on all other jobs but allows skipped jobs

.github/workflows/flowzone.yml
=> Restore protect branch input that was removed by mistake

.github/workflows/flowzone.yml
=> Only run protect branch on pull request events

.github/workflows/flowzone.yml
=> Do not include the v prefix on versioned docker tags

.github/workflows/flowzone.yml
=> Extract the new version from the changelog

.github/workflows/flowzone.yml, README.md
Resolves: https://github.com/product-os/flowzone/issues/74
=> Describe secrets and inputs with headings instead of a table

.github/workflows/flowzone.yml, README.md
=> Skip versioned commit if no changes were made by versionist

.github/workflows/flowzone.yml, README.md
=> Replace BALENA_API_KEY_PUSH secret with BALENA_API_KEY

README.md
=> Add example of configuring input to usage

.github/workflows/tests.yml, README.md
=> Set required approvals back to 1 for flowzone

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md
This simplifies the build flow and configuration of inputs
and allows for extending to additional registries in the
future.
=> Combine ghcr and dockerhub image lists into one

.github/workflows/flowzone.yml
=> Fix parsing of the changelog when repo type is not node

.github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/126
=> Require a change-type for pull requests

.github/workflows/flowzone.yml
=> Always run branch protection job and check for overall failure

.github/workflows/flowzone.yml, README.md
=> Refactor job names and dependencies

.github/workflows/flowzone.yml
=> Fix tagging of draft docker images

.github/flowzone/draft/action.yml, .github/flowzone/finalize/action.yml, .github/flowzone/test/action.yml, .github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues
=> Add composite workflow support

.github/flowzone/draft/action.yml, .github/flowzone/finalize/action.yml, .github/flowzone/test/action.yml, .github/workflows/flowzone.yml
=> Add required inputs to custom composite actions

.github/workflows/flowzone.yml
=> patch: Fix typo in custom action detection

.github/workflows/flowzone.yml
=> Fix typo in branch rules

.github/workflows/flowzone.yml, README.md
=> Remove optional inputs

.github/workflows/flowzone.yml
=> Generate changelog before running versionist

.github/workflows/flowzone.yml, README.md, tests/package.json
Resolves: https://github.com/product-os/flowzone/issues/149
=> Find the intersection of the node engines and recent LTS releases

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md
This moves the custom project logic into Project Types and
allows a single job to determine the types of events to support.
=> Replace context check with event types parser

.github/workflows/flowzone.yml, .github/workflows/tests.yml
=> Fix parsing of docker_images with newlines

.github/workflows/flowzone.yml, README.md
=> Standardize on GitHub cache for docker builds

.github/workflows/flowzone.yml
Instead make sure that Protect Branch always runs so branch
protection rules can depend on it being pass/fail and not skipped.
=> Remove All Tests and All Published jobs

.github/workflows/flowzone.yml, .github/workflows/tests.yml
=> Use a matrix for publishing docker images to multiple repositories

.github/workflows/flowzone.yml
=> Rename docker archvariant artifacts to include the sha256

README.md
Resolves: https://github.com/product-os/flowzone/issues/154
=> Document how to skip CI on the README #154

README.md
Signed-off-by: Micah Halter <micah@balena.io>
=> Fix typo in the protect_branch example

.github/workflows/flowzone.yml
=> Fix typo when checking for merge events

.github/actions/clean/action.yml, .github/workflows/flowzone.yml, README.md
These composite actions will run when a PR is closed without merging.
Resolves: https://github.com/product-os/flowzone/issues/180
=> Add support for custom clean actions

.github/workflows/flowzone.yml
=> Fix requirements for versioned commits

.github/workflows/flowzone.yml
=> Install dependencies before npm publish if there are relevant scripts

.github/workflows/flowzone.yml, README.md
Skip docker publish by default, when not explicitly set. 
resolves: #188
=> Default docker_images inputs to ''

.github/workflows/flowzone.yml
Fixing docker_images string and add empty check
=> Fixing docker_images string and add empty check

.github/workflows/flowzone.yml
=> Debug and fix npm pack issue missing grunt in publish

.github/workflows/flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/198
=> Specify balenaCloud environment

.github/workflows/flowzone.yml, README.md
=> Add Dockerfile parameter

.github/workflows/flowzone.yml, README.md
* use advanced Docker build flow (.hcl) instead
=> Revert Dockerfile parameter

.github/workflows/flowzone.yml
Run single service sut so that exit code is derived from this service
=> Test only from docker-compose.test.yml

.github/workflows/flowzone.yml, README.md
=> Dynamic runs-on

.github/workflows/flowzone.yml
=> Skip docker finalize if no docker images are specified

.github/workflows/flowzone.yml
=> Enable publishing/finalizing docker images without docker-compose tests

.github/workflows/flowzone.yml
=> Publish docker images with `v1.2.3` as well as `1.2.3`

README.md
=> WIP: Add tokens required for cloudflare pages to the README

.github/workflows/flowzone.yml
=> Automatically check out submodules recursively

.github/workflows/flowzone.yml
=> Don't try to publish to balena if `balena_slugs` is empty

.github/workflows/flowzone.yml
=> Add support for custom finalize matrices

README.md
=> Add documentation for custom job secrets/matrices

.github/workflows/flowzone.yml, README.md
=> Enable versioning by default, with a `disable_versioning` option

.github/workflows/flowzone.yml
=> Use gzip compression for the source artifact

.github/workflows/flowzone.yml, README.md
=> Add support for publishing an npm `doc` script to github pages

.github/workflows/flowzone.yml
=> Use gzip compression for the docker image artifact

README.md
This reverts commit 3ef70c9f6a5e48a5e450a58fc5a8c5313c1f8931.
=> Revert "Add tokens required for cloudflare pages to the README"

README.md
=> updates dockerhub docs

.github/workflows/flowzone.yml
=> Avoid polluting the working directory with the source.tgz by using /tmp

.github/workflows/flowzone.yml
=> Fix sha lookup when tagging main branch to finalize docker

.github/workflows/flowzone.yml
See: https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-data-type
=> Convert timeout input to a number

.github/actions/always/action.yml, .github/workflows/flowzone.yml, README.md
=> Always run custom action even if workflow is cancelled

.github/workflows/flowzone.yml
=> Always convert Docker repositories to lower case

.github/workflows/flowzone.yml
=> Pin balena-versionist/versionist versions

.github/workflows/flowzone.yml
=> Debug npm pack

.github/workflows/flowzone.yml
* if action.yml is present regadless of status of other jobs
=> Always run `custom_always` step

.github/workflows/flowzone.yml
=> Only check in the root of the working dir for npm pack files

.github/workflows/flowzone.yml
=> Only look for an npm pack in the working dir for node 6.x

README.md
=> Remove incorrect path character for `flowzone.yml`

.github/workflows/flowzone.yml
=> Fix typo on finalizing Docker tags

.github/workflows/flowzone.yml
These changes are causing problems with some repos, likely related ti testing docker images without publishing them
=> Revert merging of docker test/publish steps

README.md
=> Update readme to better explain the `protect_branch: false` intent

.github/workflows/flowzone.yml
=> Move compose environment generation

.github/workflows/flowzone.yml
=> Fix for empty COMPOSE_VARS

.github/workflows/flowzone.yml
=> Fail if generating CHANGELOG.yml fails since the bug was fixed

.github/workflows/flowzone.yml
=> Only login to registry if the NPM_TOKEN is present

.github/workflows/flowzone.yml
=> Fix adding protections to a branch that has no existing protections

flowzone.yml
=> Deduplicate more uses of extractSourceArtifact

.github/workflows/flowzone.yml, flowzone.yml
=> Fix docker pipeline when only `docker-compose.test.yml` is provided

.github/workflows/flowzone.yml, flowzone.yml
=> Bump balena-versionist version.

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md, flowzone.yml, package-lock.json
=> Custom OS matrix

.github/workflows/flowzone.yml, flowzone.yml
=> Fix broken reference to the branch or tag when finalizing docker images

.github/workflows/flowzone.yml, flowzone.yml
=> Ensure github prepare job is run before gh publish

.github/workflows/flowzone.yml, flowzone.yml
This should help with migrating projects off Landr.
=> Introducing a website type

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/76
=> Update DockerHub description on docker finalize

.github/workflows/flowzone.yml, flowzone.yml
=> Update import-gpg action to v5.2.0

.github/workflows/flowzone.yml, flowzone.yml
=> Bump versionist & balena-versionist

.github/workflows/flowzone.yml, flowzone.yml
See: https://github.com/product-os/flowzone/issues/332
=> Remove the global GHCR_TOKEN env var as it contains secrets

.github/workflows/flowzone.yml, flowzone.yml
=> Add build- prefix to npm branch tags to avoid matching semver

README.md
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
=> patch: Document need for balena publish/finalize API secret

.github/workflows/flowzone.yml, flowzone.yml
=> Only update dockerhub description on PRs to default branch

repo.yml
This is a test to see if external contributors can modify files outside of `.github/`.
=> Add yaml header to repo.yml

.github/workflows/flowzone.yml, flowzone.yml
=> Send branch to cloudflare so merge to master deploys to prod

.github/workflows/flowzone.yml, flowzone.yml
See: https://github.com/actions/checkout/issues/518
Resolves: https://github.com/product-os/flowzone/issues/353
=> Checkout the PR merge branch for pull_request_target events

.github/workflows/flowzone.yml, flowzone.yml
This will help with better identification of problems during rust builds
=> Use verbose output in calls to `cross` command

.github/workflows/flowzone.yml, flowzone.yml
Contains critical improvements to unblock docusaurus work
=> patch: Upgrade *versionist versions

README.md
=> Add a warning regarding COMPOSE_VARS secrets

.github/workflows/flowzone.yml, flowzone.yml
=> Fix dependencies for repo_config job

.github/workflows/flowzone.yml, flowzone.yml
=> Only depend on event_types

.github/workflows/flowzone.yml, flowzone.yml
=> Correct conditional (input, not job)

.github/workflows/flowzone.yml, flowzone.yml
=> Correct conitional (use bool)

.github/workflows/flowzone.yml, flowzone.yml
=> Correct conditional on empty input

.github/workflows/flowzone.yml, flowzone.yml
=> Correct missing quotes and `is_org` enumeration

.github/workflows/flowzone.yml, flowzone.yml
=> Escape required quotes

.github/workflows/flowzone.yml, flowzone.yml
=> Fix parameter handling

.github/workflows/flowzone.yml, flowzone.yml
=> Refactor description parameter handling

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
=> Single line description

.github/workflows/flowzone.yml, flowzone.yml
=> Handle forking setting edge case

.github/workflows/flowzone.yml, flowzone.yml
@klutchell this should be auto-merged as soon as it's approved (assuming it passes tests).
The only caveat I've found so far, is that if a PR is initially draft, but then marked ready, there needs to be a dummy commit pushed to force the workflow to run again. PRs can't be set to automatically merge unless they are ready for review.
=> Enable PR auto-merge

.github/workflows/flowzone.yml, flowzone.yml
=> PR auto-merge only if reviewers > 0

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/378
=> Strip docker.io prefix when updating dockerhub description

.github/workflows/flowzone.yml, flowzone.yml
=> Enhance error message for GH API branch protection

.github/workflows/flowzone.yml, flowzone.yml
=> Fix dockerhub repository output for descriptions

.github/workflows/flowzone.yml, flowzone.yml
=> Rename docusaurus-theme to docusaurus-builder

.github/renovate.json
See: https://github.com/product-os/flowzone/pull/344
See: https://github.com/product-os/flowzone/pull/386
=> Extend filematch for Renovate github-actions manager

.github/renovate.json
Perform the same steps as a pre-commit by running
npm ci and npm run test.
=> Add post-upgrade command for Renovate

.github/renovate.json
=> Fix syntax of renovate post upgrade commands

.github/renovate.json
=> renovate: run npm build instead of npm test

.github/workflows/flowzone.yml, flowzone.yml
=> Enable docusaurus website build by default

.github/workflows/flowzone.yml, flowzone.yml
See: https://github.com/balena-io/balena-sdk/pull/1272
=> Add the tests_run_on value to the custom test environment as os_value

.github/workflows/flowzone.yml, flowzone.yml
=> Mask COMPOSE_VARS secrets

.github/workflows/flowzone.yml, flowzone.yml
=> Only mask the values

flowzone.yml
=> Dedup common steps

.github/workflows/flowzone.yml, README.md, flowzone.yml
=> Install dependencies with`npm ci` for projects using npm-shrinkwrap.json

.github/renovate.json
=> renovate: Add generated flowzone workflow to ignored files

.github/workflows/flowzone.yml, flowzone.yml
=> Fix error in required checks regex

.github/workflows/flowzone.yml, flowzone.yml
=> Restore case insensitive regex

.github/workflows/flowzone.yml, flowzone.yml
The -1 syntax doesn't work and it shouldn't matter which version we are using here.
=> Index the first element of the node_versions array

.github/workflows/flowzone.yml, flowzone.yml
Previous commits changed this back to the original name for this action. 
Updating it back to the orignal title
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
=> patch: Update docusaurus action name again

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/442
=> Disable pager for git log commands to avoid error 141

.github/workflows/flowzone.yml, flowzone.yml, tests/docker-compose.test.yml
=> Pre-process compose files so we can modify them before tests

.github/workflows/flowzone.yml, flowzone.yml
Closes: #454
Signed-off-by: Christina Ying Wang <christina@balena.io>
=> Reverse docker compose file preprocessing order to favor `test` yaml

.github/workflows/flowzone.yml, flowzone.yml
Closes: #456
See: #454
Signed-off-by: Christina Ying Wang <christina@balena.io>
=> Use -f for multi-docker-compose instead of COMPOSE_FILE

.github/workflows/flowzone.yml, README.md, flowzone.yml
=> Skip updating branch protection on draft pull requests

.github/workflows/tests.yml
=> Skip e2e tests on forks

.github/workflows/flowzone.yml, flowzone.yml
=> Make GitHub PR automerge opt-in for now

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/469, https://github.com/product-os/flowzone/issues/442
=> Fix missing tags on merge events

.github/workflows/flowzone.yml, flowzone.yml
=> Fix parsing of tags when versioning is disabled

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/195
=> Block publish jobs until all tests are success or skipped

.github/workflows/flowzone.yml, flowzone.yml
=> Avoid extra tagging when merging unversioned PRs

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
This will ensure that each push appears unique
and retriggers the downstream e2e jobs.
=> Add a line comment to downstream e2e commits

.github/workflows/flowzone.yml, flowzone.yml
=> Use credentials for versionist, enabling private nested changelogs

.github/workflows/flowzone.yml, flowzone.yml, tests/entrypoint.sh
=> Avoid leaking secrets from COMPOSE_VARS

.github/workflows/flowzone.yml, flowzone.yml
=> Use anchors to set the GitHub CLI environment

.github/workflows/flowzone.yml, flowzone.yml
=> Check if package-lock.json exists to enable caching

.github/workflows/flowzone.yml, flowzone.yml
=> Skip applying branch protection if rules are unchanged

.github/workflows/flowzone.yml, flowzone.yml
Also move check for draft PR to an anchor, and remove redundant dependencies.
=> Remove versioned source from protect branch steps

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md, flowzone.yml
@klutchell this PR should be ready to go, please review when you get a chance. There are some structural changes in here, especially around tests.
=> Ephemeral access tokens

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
=> Correct regression

.github/workflows/flowzone.yml, flowzone.yml
=> Correct external contribution restrictions

.github/workflows/flowzone.yml, flowzone.yml
=> Add missing ephemeral token steps

.github/workflows/flowzone.yml, flowzone.yml
=> Fix conditional when branch rules have changed

.github/workflows/flowzone.yml, flowzone.yml
Allows pulling of private images from ghcr.io and docker.io on balena-builders.
=> balena registry secrets

.github/workflows/flowzone.yml, flowzone.yml
More clarity on why the Cloudflare command failed. Currently even the errors are piped into the summary. 
This adds output logs to both the action run and flowzone summary.
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
=> Install custom Wrangler version & show command output

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/518
=> Compress docker artifacts before uploading

.github/workflows/flowzone.yml, flowzone.yml
=> Fix missing env_file when parsing docker-compose

.github/workflows/flowzone.yml, flowzone.yml
=> Pin to a fixed release of QEMU binfmt

.github/workflows/tests.yml, README.md
See: https://github.com/product-os/flowzone/issues/549
This is just a change to documentation. The real fix is updating all the workflows deployed in production repos.
=> Prevent duplicate workflows for pull_request and pull_request_target

.github/workflows/bulk-patch.yml, .github/workflows/tests.yml, BULK-PATCH.md
Also fix parsing of comma-separated inputs.
=> Remove auto-merge enable step

.github/workflows/flowzone.yml, flowzone.yml
This will force users to update their workflows
to avoid duplicate runs that could break branch protection.
=> Reject duplicate workflow calls

.github/workflows/flowzone.yml, flowzone.yml
=> Add missing job dependency in cargo_publish

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
=> Reject use of self-hosted runners for external pull requests

.github/workflows/flowzone.yml, flowzone.yml
This will prevent duplicate runs when both triggers are enabled.
=> Reject internal pull requests using pull_request_target

.github/workflows/e2e.yml, .github/workflows/patch.yml, docs/workflow-dispatch.md
=> e2e: Use JSON inputs for repositories and required checks

.github/workflows/flowzone.yml, flowzone.yml
=> Install crane for docker finalize

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/576
=> Use the bake target for the ref.name docker image label

.github/workflows/flowzone.yml, flowzone.yml
=> Restore missing checkout step for unversioned external pull requests

.github/actions/always/action.yml, .github/actions/clean/action.yml, .github/actions/finalize/action.yml, .github/actions/publish/action.yml, .github/actions/test/action.yml
=> Add app token generation to custom action examples

.github/workflows/flowzone.yml, README.md, flowzone.yml
This does not wait for required checks to finish, it only
waits until they are returned via the GH API.
Resolves: https://github.com/product-os/flowzone/issues/549
=> Toggle auto-merge after required checks have registered

.github/workflows/flowzone.yml, flowzone.yml
=> Fix run conditions for tagged source

.github/workflows/flowzone.yml, flowzone.yml
=> Restore missing dependency to tagged source job

.github/workflows/flowzone.yml, flowzone.yml
Resolves: https://github.com/product-os/flowzone/issues/582
=> Skip npm pack for private packages

.github/workflows/flowzone.yml, flowzone.yml
These jobs were performing nrealy the same functions and combining them reduces the paths required for testing.
=> Combine tagged source and versioned source jobs

.github/workflows/flowzone.yml, flowzone.yml
=> Prevent waiting for jobs that are part of the same workflow

.github/workflows/e2e.yml, .github/workflows/flowzone.yml, flowzone.yml
This job was causing dependency loops for any required
job that dependend on Flowzone.
For now we will see if the GH auto-merge toggle behaves as designed.
=> Remove wait for required checks

.github/renovate.json
=> Only bump the minor version for github actions major revisions

.github/workflows/flowzone.yml, flowzone.yml
On repos with many files this can overwhelm the logs.
=> Disable verbose extracting of source artifacts

.github/workflows/e2e.yml
=> Adds patch bump to commit footer on e2e

.github/workflows/e2e.yml, .github/workflows/patch.yml
=> Adds company-os installation ID

.github/workflows/flowzone.yml, README.md, flowzone.yml, tests/pyproject.toml
=> Publishes python(poetry) packages to PyPI

.github/workflows/flowzone.yml, flowzone.yml
=> Fixes python_finalize name

.github/workflows/flowzone.yml, flowzone.yml
=> Fixes typo in python_finalize

.github/workflows/flowzone.yml, flowzone.yml, tests/pyproject.toml, tests/python_test/__init__.py, tests/tests/test_python_test.py
=> Builds python release on finalize

.github/workflows/flowzone.yml, flowzone.yml
=> Skip docker save and upload when publish is disabled

.github/workflows/flowzone.yml, flowzone.yml
=> Only pack and upload for the latest node version

.github/workflows/tests.yml
=> Test custom actions on a range of hosted runners

.github/workflows/flowzone.yml, flowzone.yml
=> Update versionist to v7 supporting yq v4

.github/workflows/flowzone.yml, flowzone.yml
tests:
* internal contribution (control) [here](https://github.com/balena-io/open-balena-vpn/actions/runs/5127328650/jobs/9222824010)
* external contribution [here](https://github.com/balena-io/open-balena-vpn/actions/runs/5127176594/jobs/9222770151#step:7:116).
=> whitelist external PRs on self-hosted

.github/workflows/flowzone.yml, flowzone.yml
=> Fix log level tag

.github/workflows/flowzone.yml, flowzone.yml
=> Missing AWS auth on finalize

.github/workflows/flowzone.yml, flowzone.yml
=> Separate parameters with a space

.github/workflows/flowzone.yml, flowzone.yml
=> Handle all cases of CFN waits

.github/workflows/flowzone.yml, flowzone.yml
=> Dedup AWS steps

.github/workflows/flowzone.yml, flowzone.yml
For PRT this sha is from master, not the PR branch.
=> Do not use github.sha for pull request target events

.github/workflows/flowzone.yml, README.md, flowzone.yml
=> consider CloudFormation jobs

.github/workflows/flowzone.yml, flowzone.yml
=> CFN params optional

.github/workflows/flowzone.yml, flowzone.yml
=> correct bucket name

.github/workflows/flowzone.yml, flowzone.yml
=> Unpin versionist & balena-versionist to pick up non-breaking changes

.github/workflows/flowzone.yml, flowzone.yml
=> handle quoted strings

.github/workflows/flowzone.yml, README.md, flowzone.yml
Add `terraform` project type and configures with TF state stored in Kubernetes cluster(s) (e.g.):
```
terraform_projects: >
{
"projects": [
{
"main_tf": "terraform/github"
},
{
"main_tf": "terraform/authentication"
},
...
]
}
```
Test: https://github.com/product-os/environment-staging/actions/runs/5326084442/jobs/9648989905
* also includes reliability settings for AWS/CFN and TF jobs
=> Terraform project type

.github/workflows/flowzone.yml, flowzone.yml
=> Missing TF init

.github/workflows/flowzone.yml, flowzone.yml
=> warn on remove

.github/workflows/flowzone.yml, flowzone.yml
=> look at the result

.github/workflows/flowzone.yml, flowzone.yml
=> correct change set warnings

.github/workflows/flowzone.yml, flowzone.yml
=> correct removal detection

.github/workflows/flowzone.yml, flowzone.yml
AWS_REGION configurable based on CFN input.
=> matrix AWS region

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md, flowzone.yml
=> Add GPT pull request reviews via gpt-review package

.github/workflows/flowzone.yml, flowzone.yml
Otherwise we blindly fall back to FLOWZONE_TOKEN with no warning
=> Get Github app token before cloning versioned source

.github/workflows/flowzone.yml, flowzone.yml
This command is more likely to catch errors that are missed by curl.
=> Use gh api command to create blobs

.github/workflows/flowzone.yml, README.md, flowzone.yml
=> Remove token permissions that were removed from the GitHub app

.github/workflows/flowzone.yml, README.md, flowzone.yml
=> Remove read access for members and actions

.github/workflows/flowzone.yml, README.md, flowzone.yml
=> Remove token permissions for statuses, checks, and secrets

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
This will catch any missing dependencies or configuration on our self-hosted runners required to completely
avoid GitHub hosted runners on private repos.
=> Test all job types on self-hosted runners

.github/workflows/flowzone.yml, flowzone.yml
=> fix multi-line inputs

.github/workflows/flowzone.yml, flowzone.yml
=> Switch to pull_request.user.type property for identifying bots

.github/workflows/flowzone.yml, flowzone.yml
=> Fix resolving of dockerhub image slug for readme publishing

.github/workflows/flowzone.yml, flowzone.yml
=> Only setup poetry if python setup was successful

flowzone.yml
=> Use full semver for aws-actions/configure-aws-credentials

flowzone.yml
=> Track the docker/metadata-action full semver tag

.github/workflows/flowzone.yml, flowzone.yml
=> Pin all actions to full semver

.github/workflows/tests.yml, tests/docker-bake.hcl
=> Skip testing on armv7 self-hosted runners

.github/workflows/flowzone.yml, flowzone.yml
=> Return http response status codes for some gh api commands

.github/workflows/flowzone.yml, flowzone.yml
=> Fall back to curl if github CLI fails to update objects

.github/workflows/flowzone.yml, flowzone.yml
Otherwise we lose access to private submodules on clone.
See: https://github.com/product-os/flowzone/pull/730
=> Restore access to all repositories when cloning sources

.github/workflows/flowzone.yml, flowzone.yml
See: https://github.com/cloudflare/wrangler-action/pull/166
=> Specify packageManager input for latest wranger action

.github/workflows/flowzone.yml, flowzone.yml
=> Add support for node 20 in npm tests

.github/workflows/flowzone.yml, flowzone.yml
Depends-on: https://github.com/product-os/flowzone/pull/788
=> Bump the default fallback node version to 20.x

.github/workflows/flowzone.yml, flowzone.yml
=> Allow registering QEMU binfmt on self-hosted X64

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
Example merged bake file output including additional cache-from sources:
```hcl
{
"target": {
"default": {
"attest": [
"type=provenance,disabled=true"
],
"context": ".",
"dockerfile": "Dockerfile",
"args": {
"DOCKER_META_IMAGES": "sut,localhost:5000/sut,ghcr.io/product-os/flowzone",
"DOCKER_META_VERSION": "0ea38579ec88bd9ef8096a361f2ea57d709c46b4"
},
"labels": {
"org.opencontainers.image.created": "2023-11-10T15:00:20.963Z",
"org.opencontainers.image.description": "Reusable, opinionated, zero-conf workflows for GitHub actions",
"org.opencontainers.image.licenses": "Apache-2.0",
"org.opencontainers.image.ref.name": "default",
"org.opencontainers.image.revision": "da3329194cdb73d3bada2a215fe5a3fb76dbd9b9",
"org.opencontainers.image.source": "https://github.com/product-os/flowzone", …
```
=> Add draft and final tags to docker cache sources

.github/workflows/flowzone.yml, flowzone.yml
=> Check that docker images list is provided before generating cache tags

.github/workflows/flowzone.yml, flowzone.yml
=> Always publish GitHub releases even without artifacts

.github/workflows/flowzone.yml, flowzone.yml
=> Handle a null value from the docker cache meta step

.github/workflows/flowzone.yml, flowzone.yml
=> Catch errors when fetching branch protection rules

.github/workflows/flowzone.yml, flowzone.yml
=> Parse messages and http codes to determine success

.github/workflows/flowzone.yml, flowzone.yml
=> Fix CloudFlare pages not deploying

.github/workflows/flowzone.yml, flowzone.yml
=> Handle errors when there are no artifacts to publish

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md, flowzone.yml
=> Remove GPT Review feature

.github/workflows/flowzone.yml, flowzone.yml
=> Avoid failing workflow when branch is unprotected

.github/actions/test/action.yml, .github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
See: https://balena.fibery.io/Inputs/Research/Figure-out-how-to-CI-test-KVM-features-with-GitHub-Actions-446
=> Enable KVM features on GitHub hosted runners

.github/workflows/flowzone.yml, flowzone.yml
=> Clean up errors when aws region is unset

.github/workflows/flowzone.yml, flowzone.yml
We need to add handling for releases without any artifacts.
=> Revert "Update softprops/action-gh-release action to v2"

.github/workflows/flowzone.yml, flowzone.yml
This is ready to go.
* https://github.com/balena-io/deploy-to-balena-action/issues/194
* https://github.com/balena-io/deploy-to-balena-action/pull/341
=> use balena cli to set release notes

.github/workflows/flowzone.yml, flowzone.yml
e.g.
https://github.com/balena-io/environment-production/actions/runs/8381211777/job/22955160645#step:4:2054
=> repositories with submodules fail

.github/workflows/flowzone.yml, flowzone.yml
=> lint CloudFormation templates

.github/workflows/flowzone.yml, flowzone.yml
* W3045 Consider using AWS::S3::BucketPolicy instead of AccessControl
=> ignore S3 linter warning

.github/workflows/flowzone.yml, flowzone.yml
=> Fix docker finalize matrix mapping

.github/workflows/flowzone.yml, flowzone.yml, package.json
This does not apply to repos using Flowzone yet,
only self-checks via pre-commit hooks.
See: https://github.com/product-os/flowzone/pull/968
=> Enable shellcheck via actionlint npm lint command

.github/workflows/flowzone.yml, .github/workflows/tests.yml, README.md, flowzone.yml
This is a far more flexible implentation allowing
any combination of matrix strategies for custom jobs.
=> Support custom values as a matrix instead of a list

.github/workflows/flowzone.yml, flowzone.yml
.. otherwise we run out of runners processing empty change-sets (e.g.)
* https://github.com/balena-io/environment-staging/actions/runs/8696710589/job/23850671908#step:5:26899
=> only run AWS/CFN updates if templates changed

.github/workflows/tests.yml
=> Test on self-actuated runners

.github/workflows/flowzone.yml, flowzone.yml
.. attempt to fix [this](https://github.com/balena-io/environment-production/pull/2249#issuecomment-2059281138)
testing:
* https://github.com/balena-io/environment-staging/pull/3339
* https://github.com/balena-io/environment-staging/pull/3340
* https://github.com/balena-io/environment-staging/pull/3341
=> check parent commit for changed files on merge

.github/workflows/flowzone.yml, flowzone.yml
=> Setup skopeo for runners that do not have it preinstalled

.github/workflows/flowzone.yml, flowzone.yml
The previous action has a number of issues and doesn't work.
=> Use a new setup skopeo action

.github/workflows/flowzone.yml, flowzone.yml
=> Fix mapping errors in custom matrix definitions

.github/workflows/flowzone.yml, flowzone.yml
=> add missing contents write permissions to create tags

.github/workflows/flowzone.yml, flowzone.yml
=> Provide the tag env var when creating release notes

.github/workflows/flowzone.yml, flowzone.yml
Some self-hosted runners may not have this binary, or the version that we want.
=> Setup AWS CLI when starting jobs that require it

.github/workflows/flowzone.yml, flowzone.yml
The project was moved as we are using it in
production and it is no longer experimental.
=> Point to the new org for setup-skopeo-action

.github/workflows/flowzone.yml, flowzone.yml
* should avoid these [phantom failures](https://github.com/balena-io/environment-production/actions/runs/9017695617)
=> don't try to finalize empty stack matrix

.github/workflows/flowzone.yml, flowzone.yml
.. testing(ed) [here](https://github.com/balena-io/environment-production/pull/2339#issuecomment-2103488469); [here](https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/Deploys/near/437901316)
* refactor conditional logic style (bools at the end)
* add quick visuals to PR comment (reactions)
=> fix conditional logic that finds release notes in PR comments

flowzone.yml
=> correct Renovate binfmt

.github/workflows/flowzone.yml, flowzone.yml
To support the `dbt-project` repository type
=> Pin `balena-versionist` to v0.15.0

.github/workflows/flowzone.yml, flowzone.yml
This should re-enable publishing of READMEs
as DockerHub descriptions on finalize.
=> Fix string process for dockerhub images

.github/workflows/flowzone.yml, flowzone.yml, package.json
This will require someone during the cooldown to help to fix projects with bad shell syntax in their workflows.
=> BREAKING: Enforce workflow shellcheck via actionlint

.github/workflows/flowzone.yml, flowzone.yml
.. resolves [this](https://github.com/balena-io/environment-production/actions/runs/9798835624/job/27058018175?pr=2500#step:14:25)
=> Quoting string with spaces breaks cfn-lint

.github/workflows/flowzone.yml, flowzone.yml
---
Tested with https://github.com/product-os/hubot/pull/531
=> Dynamically decide node version to use for SBOM

.github/workflows/flowzone.yml, flowzone.yml
Otherwise a custom matrix without the os property will fail.
=> Default to global runs_on setting when custom os is unset

.github/workflows/flowzone.yml, flowzone.yml
Removes the workaround added to deal with issue npm/cli#7657 as that issue has now been closed.
=> Unpin Node version

.github/workflows/flowzone.yml, flowzone.yml
=> Remove node 16 as it went EOL on 2023-09-11

.github/workflows/flowzone.yml, flowzone.yml
=> Share auth config across all `actions/checkout` usage

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
See: https://balena.fibery.io/Work/Improvement/Define-explicit-permissions-in-Flowzone-for-GITHUB_TOKEN-2307
=> Require jobs to describe GITHUB_TOKEN permissions explicitly

.github/workflows/flowzone.yml, flowzone.yml
See [this](https://github.com/balena-io/balena-cloud/actions/runs/11783098446/job/32821736712#step:4:59).
=> Website publish needs contents:read

.github/workflows/flowzone.yml, flowzone.yml
See: https://github.com/product-os/flowzone/actions/runs/11824092189/job/32944917913
=> Restore missing token when creating git reference

.github/workflows/flowzone.yml, flowzone.yml
=> Release notes require "pull_requests": "read"

.github/workflows/flowzone.yml, .pre-commit-config.yaml, flowzone.yml, tests/docker-compose.test.yml
This step will fail if the hooks find any differences after running. Pre-commit hooks are useful projects for that don't use npm & husky.
See https://pre-commit.com for more information.
=> Run pre-commit hooks if a config file exists in the project

.github/workflows/flowzone.yml, flowzone.yml
=> Make clear that unedited release notes will not be posted

.github/workflows/flowzone.yml, flowzone.yml
=> Allow renovate to bump buildx versions

.github/workflows/flowzone.yml, .husky/pre-commit, flowzone.yml
This is a more concise and secure method and avoids the risks of jq processing typos.
=> Replace json array builder shell with github-script

.github/workflows/flowzone.yml, flowzone.yml
This PR resolves 29 code-scanning warnings.
master: https://github.com/product-os/flowzone/security/code-scanning
branch: https://github.com/product-os/flowzone/security/code-scanning?query=is%3Aopen+pr%3A1298
=> Replace shell steps with github-script steps

.github/workflows/flowzone.yml, .github/workflows/tests.yml, flowzone.yml
=> Fix parsing of bake targets input

.github/workflows/flowzone.yml, flowzone.yml
The output should have the value `true` if the doc script exists
=> Set correct npm_docs output value

.github/workflows/flowzone.yml, flowzone.yml
Supersedes https://github.com/product-os/flowzone/pull/1275
=> Update QEMU tonistiigi/binfmt to v9.2.0-46

.github/workflows/flowzone.yml, flowzone.yml
Tested here:
- https://github.com/product-os/.github/actions/runs/13144587180/job/36679622826?pr=275
- https://github.com/product-os/.github/actions/runs/13143970107/job/36677607493?pr=275 (with version bump)
=> Fix parsing of tonistiigi/binfmt versioning

.github/workflows/flowzone.yml, flowzone.yml
This provides better control over the output and
returns the new version directly.
=> Run balena-versionist via github-script

.github/workflows/flowzone.yml, flowzone.yml
Fix an issue where we were producing a json file with an xml extension for node/npm projects.
=> patch: fix sbom filename extension

.github/workflows/flowzone.yml, flowzone.yml
=> Mark pre-commit hooks as required if the config exists

.github/workflows/flowzone.yml, flowzone.yml
=> Default to NodeJS 22.x when engines property cannot be satisfied

.github/workflows/flowzone.yml, flowzone.yml
This includes a fix to balena-semver with major|minor|patch above 1000.
See: https://github.com/balena-io-modules/balena-semver/pull/92
See: https://github.com/product-os/versionist/pull/257
See: https://balena.zulipchat.com/#narrow/channel/346007-balena-io.2FbalenaCloud/topic/balenaMachine.20repo.20stuck.20on.20v14.2E1.2E1000/near/503081215
=> Update product-os/versionist to v8.0.0

.github/workflows/flowzone.yml, flowzone.yml
> helps with codifying opaque `COMPOSE_VARS`
e.g. https://github.com/product-os/flowzone/actions/runs/13503321740/job/37727014991#step:12:26
=> Show COMPOSE_VARS secrets name(s)

.github/workflows/flowzone.yml, flowzone.yml
=> Test all targets and features for Rust projects

.github/workflows/flowzone.yml, flowzone.yml
=> Use the max supported node version during website publish

.github/workflows/flowzone.yml, flowzone.yml
=> Remove deprecated input poll-interval from review-commit-action

.github/workflows/flowzone.yml, flowzone.yml
=> Add nodejs 24 to the test matrix as it will be the next LTS

.github/workflows/flowzone.yml, flowzone.yml
=> Grant `actions: read` permission to NPM finalize

README.md
=> Update cargo workpace documentation on README
